// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: atlas/vehicle_agent_channel.proto

package vehicleagentchannelpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VehicleAgentToBackend struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	VehicleAgentId string                 `protobuf:"bytes,1,opt,name=vehicle_agent_id,json=vehicleAgentId,proto3" json:"vehicle_agent_id,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*VehicleAgentToBackend_Hello
	//	*VehicleAgentToBackend_CommandStatus
	//	*VehicleAgentToBackend_Heartbeat
	//	*VehicleAgentToBackend_Telemetry
	//	*VehicleAgentToBackend_MissionExecutionStatus
	Payload       isVehicleAgentToBackend_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VehicleAgentToBackend) Reset() {
	*x = VehicleAgentToBackend{}
	mi := &file_atlas_vehicle_agent_channel_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VehicleAgentToBackend) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VehicleAgentToBackend) ProtoMessage() {}

func (x *VehicleAgentToBackend) ProtoReflect() protoreflect.Message {
	mi := &file_atlas_vehicle_agent_channel_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VehicleAgentToBackend.ProtoReflect.Descriptor instead.
func (*VehicleAgentToBackend) Descriptor() ([]byte, []int) {
	return file_atlas_vehicle_agent_channel_proto_rawDescGZIP(), []int{0}
}

func (x *VehicleAgentToBackend) GetVehicleAgentId() string {
	if x != nil {
		return x.VehicleAgentId
	}
	return ""
}

func (x *VehicleAgentToBackend) GetPayload() isVehicleAgentToBackend_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *VehicleAgentToBackend) GetHello() *VehicleAgentHello {
	if x != nil {
		if x, ok := x.Payload.(*VehicleAgentToBackend_Hello); ok {
			return x.Hello
		}
	}
	return nil
}

func (x *VehicleAgentToBackend) GetCommandStatus() *CommandStatus {
	if x != nil {
		if x, ok := x.Payload.(*VehicleAgentToBackend_CommandStatus); ok {
			return x.CommandStatus
		}
	}
	return nil
}

func (x *VehicleAgentToBackend) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Payload.(*VehicleAgentToBackend_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *VehicleAgentToBackend) GetTelemetry() *Telemetry {
	if x != nil {
		if x, ok := x.Payload.(*VehicleAgentToBackend_Telemetry); ok {
			return x.Telemetry
		}
	}
	return nil
}

func (x *VehicleAgentToBackend) GetMissionExecutionStatus() *MissionExecutionStatus {
	if x != nil {
		if x, ok := x.Payload.(*VehicleAgentToBackend_MissionExecutionStatus); ok {
			return x.MissionExecutionStatus
		}
	}
	return nil
}

type isVehicleAgentToBackend_Payload interface {
	isVehicleAgentToBackend_Payload()
}

type VehicleAgentToBackend_Hello struct {
	Hello *VehicleAgentHello `protobuf:"bytes,2,opt,name=hello,proto3,oneof"`
}

type VehicleAgentToBackend_CommandStatus struct {
	CommandStatus *CommandStatus `protobuf:"bytes,3,opt,name=command_status,json=commandStatus,proto3,oneof"`
}

type VehicleAgentToBackend_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,4,opt,name=heartbeat,proto3,oneof"`
}

type VehicleAgentToBackend_Telemetry struct {
	Telemetry *Telemetry `protobuf:"bytes,5,opt,name=telemetry,proto3,oneof"`
}

type VehicleAgentToBackend_MissionExecutionStatus struct {
	MissionExecutionStatus *MissionExecutionStatus `protobuf:"bytes,6,opt,name=mission_execution_status,json=missionExecutionStatus,proto3,oneof"`
}

func (*VehicleAgentToBackend_Hello) isVehicleAgentToBackend_Payload() {}

func (*VehicleAgentToBackend_CommandStatus) isVehicleAgentToBackend_Payload() {}

func (*VehicleAgentToBackend_Heartbeat) isVehicleAgentToBackend_Payload() {}

func (*VehicleAgentToBackend_Telemetry) isVehicleAgentToBackend_Payload() {}

func (*VehicleAgentToBackend_MissionExecutionStatus) isVehicleAgentToBackend_Payload() {}

type BackendToVehicleAgent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*BackendToVehicleAgent_Command
	//	*BackendToVehicleAgent_Ping
	//	*BackendToVehicleAgent_MissionExecution
	Payload       isBackendToVehicleAgent_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BackendToVehicleAgent) Reset() {
	*x = BackendToVehicleAgent{}
	mi := &file_atlas_vehicle_agent_channel_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackendToVehicleAgent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackendToVehicleAgent) ProtoMessage() {}

func (x *BackendToVehicleAgent) ProtoReflect() protoreflect.Message {
	mi := &file_atlas_vehicle_agent_channel_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackendToVehicleAgent.ProtoReflect.Descriptor instead.
func (*BackendToVehicleAgent) Descriptor() ([]byte, []int) {
	return file_atlas_vehicle_agent_channel_proto_rawDescGZIP(), []int{1}
}

func (x *BackendToVehicleAgent) GetPayload() isBackendToVehicleAgent_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *BackendToVehicleAgent) GetCommand() *CommandEnvelope {
	if x != nil {
		if x, ok := x.Payload.(*BackendToVehicleAgent_Command); ok {
			return x.Command
		}
	}
	return nil
}

func (x *BackendToVehicleAgent) GetPing() *Ping {
	if x != nil {
		if x, ok := x.Payload.(*BackendToVehicleAgent_Ping); ok {
			return x.Ping
		}
	}
	return nil
}

func (x *BackendToVehicleAgent) GetMissionExecution() *MissionExecutionEnvelope {
	if x != nil {
		if x, ok := x.Payload.(*BackendToVehicleAgent_MissionExecution); ok {
			return x.MissionExecution
		}
	}
	return nil
}

type isBackendToVehicleAgent_Payload interface {
	isBackendToVehicleAgent_Payload()
}

type BackendToVehicleAgent_Command struct {
	Command *CommandEnvelope `protobuf:"bytes,1,opt,name=command,proto3,oneof"`
}

type BackendToVehicleAgent_Ping struct {
	Ping *Ping `protobuf:"bytes,2,opt,name=ping,proto3,oneof"`
}

type BackendToVehicleAgent_MissionExecution struct {
	MissionExecution *MissionExecutionEnvelope `protobuf:"bytes,3,opt,name=mission_execution,json=missionExecution,proto3,oneof"`
}

func (*BackendToVehicleAgent_Command) isBackendToVehicleAgent_Payload() {}

func (*BackendToVehicleAgent_Ping) isBackendToVehicleAgent_Payload() {}

func (*BackendToVehicleAgent_MissionExecution) isBackendToVehicleAgent_Payload() {}

type VehicleAgentHello struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	DroneId             string                 `protobuf:"bytes,1,opt,name=drone_id,json=droneId,proto3" json:"drone_id,omitempty"`
	VehicleAgentVersion string                 `protobuf:"bytes,2,opt,name=vehicle_agent_version,json=vehicleAgentVersion,proto3" json:"vehicle_agent_version,omitempty"`
	DroneName           string                 `protobuf:"bytes,3,opt,name=drone_name,json=droneName,proto3" json:"drone_name,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *VehicleAgentHello) Reset() {
	*x = VehicleAgentHello{}
	mi := &file_atlas_vehicle_agent_channel_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VehicleAgentHello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VehicleAgentHello) ProtoMessage() {}

func (x *VehicleAgentHello) ProtoReflect() protoreflect.Message {
	mi := &file_atlas_vehicle_agent_channel_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VehicleAgentHello.ProtoReflect.Descriptor instead.
func (*VehicleAgentHello) Descriptor() ([]byte, []int) {
	return file_atlas_vehicle_agent_channel_proto_rawDescGZIP(), []int{2}
}

func (x *VehicleAgentHello) GetDroneId() string {
	if x != nil {
		return x.DroneId
	}
	return ""
}

func (x *VehicleAgentHello) GetVehicleAgentVersion() string {
	if x != nil {
		return x.VehicleAgentVersion
	}
	return ""
}

func (x *VehicleAgentHello) GetDroneName() string {
	if x != nil {
		return x.DroneName
	}
	return ""
}

type Heartbeat struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	VehicleAgentVersion string                 `protobuf:"bytes,1,opt,name=vehicle_agent_version,json=vehicleAgentVersion,proto3" json:"vehicle_agent_version,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_atlas_vehicle_agent_channel_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_atlas_vehicle_agent_channel_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_atlas_vehicle_agent_channel_proto_rawDescGZIP(), []int{3}
}

func (x *Heartbeat) GetVehicleAgentVersion() string {
	if x != nil {
		return x.VehicleAgentVersion
	}
	return ""
}

type Telemetry struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ObservedAt        string                 `protobuf:"bytes,1,opt,name=observed_at,json=observedAt,proto3" json:"observed_at,omitempty"`
	BatteryPercent    float64                `protobuf:"fixed64,2,opt,name=battery_percent,json=batteryPercent,proto3" json:"battery_percent,omitempty"`
	RelativeAltitudeM float64                `protobuf:"fixed64,3,opt,name=relative_altitude_m,json=relativeAltitudeM,proto3" json:"relative_altitude_m,omitempty"`
	FlightMode        string                 `protobuf:"bytes,4,opt,name=flight_mode,json=flightMode,proto3" json:"flight_mode,omitempty"`
	Armed             bool                   `protobuf:"varint,5,opt,name=armed,proto3" json:"armed,omitempty"`
	InAir             bool                   `protobuf:"varint,6,opt,name=in_air,json=inAir,proto3" json:"in_air,omitempty"`
	Latitude          float64                `protobuf:"fixed64,7,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude         float64                `protobuf:"fixed64,8,opt,name=longitude,proto3" json:"longitude,omitempty"`
	HeadingDeg        float64                `protobuf:"fixed64,9,opt,name=heading_deg,json=headingDeg,proto3" json:"heading_deg,omitempty"`
	GpsFix            string                 `protobuf:"bytes,10,opt,name=gps_fix,json=gpsFix,proto3" json:"gps_fix,omitempty"`
	SatellitesVisible int32                  `protobuf:"varint,11,opt,name=satellites_visible,json=satellitesVisible,proto3" json:"satellites_visible,omitempty"`
	HomePositionSet   bool                   `protobuf:"varint,12,opt,name=home_position_set,json=homePositionSet,proto3" json:"home_position_set,omitempty"`
	Source            string                 `protobuf:"bytes,13,opt,name=source,proto3" json:"source,omitempty"`
	GroundSpeedMps    float64                `protobuf:"fixed64,14,opt,name=ground_speed_mps,json=groundSpeedMps,proto3" json:"ground_speed_mps,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Telemetry) Reset() {
	*x = Telemetry{}
	mi := &file_atlas_vehicle_agent_channel_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Telemetry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Telemetry) ProtoMessage() {}

func (x *Telemetry) ProtoReflect() protoreflect.Message {
	mi := &file_atlas_vehicle_agent_channel_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Telemetry.ProtoReflect.Descriptor instead.
func (*Telemetry) Descriptor() ([]byte, []int) {
	return file_atlas_vehicle_agent_channel_proto_rawDescGZIP(), []int{4}
}

func (x *Telemetry) GetObservedAt() string {
	if x != nil {
		return x.ObservedAt
	}
	return ""
}

func (x *Telemetry) GetBatteryPercent() float64 {
	if x != nil {
		return x.BatteryPercent
	}
	return 0
}

func (x *Telemetry) GetRelativeAltitudeM() float64 {
	if x != nil {
		return x.RelativeAltitudeM
	}
	return 0
}

func (x *Telemetry) GetFlightMode() string {
	if x != nil {
		return x.FlightMode
	}
	return ""
}

func (x *Telemetry) GetArmed() bool {
	if x != nil {
		return x.Armed
	}
	return false
}

func (x *Telemetry) GetInAir() bool {
	if x != nil {
		return x.InAir
	}
	return false
}

func (x *Telemetry) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *Telemetry) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *Telemetry) GetHeadingDeg() float64 {
	if x != nil {
		return x.HeadingDeg
	}
	return 0
}

func (x *Telemetry) GetGpsFix() string {
	if x != nil {
		return x.GpsFix
	}
	return ""
}

func (x *Telemetry) GetSatellitesVisible() int32 {
	if x != nil {
		return x.SatellitesVisible
	}
	return 0
}

func (x *Telemetry) GetHomePositionSet() bool {
	if x != nil {
		return x.HomePositionSet
	}
	return false
}

func (x *Telemetry) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Telemetry) GetGroundSpeedMps() float64 {
	if x != nil {
		return x.GroundSpeedMps
	}
	return 0
}

type CommandEnvelope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommandId     string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	DroneId       string                 `protobuf:"bytes,2,opt,name=drone_id,json=droneId,proto3" json:"drone_id,omitempty"`
	CommandType   string                 `protobuf:"bytes,3,opt,name=command_type,json=commandType,proto3" json:"command_type,omitempty"`
	RequestedBy   string                 `protobuf:"bytes,4,opt,name=requested_by,json=requestedBy,proto3" json:"requested_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandEnvelope) Reset() {
	*x = CommandEnvelope{}
	mi := &file_atlas_vehicle_agent_channel_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandEnvelope) ProtoMessage() {}

func (x *CommandEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_atlas_vehicle_agent_channel_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandEnvelope.ProtoReflect.Descriptor instead.
func (*CommandEnvelope) Descriptor() ([]byte, []int) {
	return file_atlas_vehicle_agent_channel_proto_rawDescGZIP(), []int{5}
}

func (x *CommandEnvelope) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *CommandEnvelope) GetDroneId() string {
	if x != nil {
		return x.DroneId
	}
	return ""
}

func (x *CommandEnvelope) GetCommandType() string {
	if x != nil {
		return x.CommandType
	}
	return ""
}

func (x *CommandEnvelope) GetRequestedBy() string {
	if x != nil {
		return x.RequestedBy
	}
	return ""
}

type CommandStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommandId     string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	State         string                 `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	ResultMessage string                 `protobuf:"bytes,3,opt,name=result_message,json=resultMessage,proto3" json:"result_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandStatus) Reset() {
	*x = CommandStatus{}
	mi := &file_atlas_vehicle_agent_channel_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandStatus) ProtoMessage() {}

func (x *CommandStatus) ProtoReflect() protoreflect.Message {
	mi := &file_atlas_vehicle_agent_channel_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandStatus.ProtoReflect.Descriptor instead.
func (*CommandStatus) Descriptor() ([]byte, []int) {
	return file_atlas_vehicle_agent_channel_proto_rawDescGZIP(), []int{6}
}

func (x *CommandStatus) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *CommandStatus) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *CommandStatus) GetResultMessage() string {
	if x != nil {
		return x.ResultMessage
	}
	return ""
}

type MissionExecutionEnvelope struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ExecutionId      string                 `protobuf:"bytes,1,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	MissionId        string                 `protobuf:"bytes,2,opt,name=mission_id,json=missionId,proto3" json:"mission_id,omitempty"`
	DroneId          string                 `protobuf:"bytes,3,opt,name=drone_id,json=droneId,proto3" json:"drone_id,omitempty"`
	Action           string                 `protobuf:"bytes,4,opt,name=action,proto3" json:"action,omitempty"`
	RequestedBy      string                 `protobuf:"bytes,5,opt,name=requested_by,json=requestedBy,proto3" json:"requested_by,omitempty"`
	Waypoints        []*MissionWaypoint     `protobuf:"bytes,6,rep,name=waypoints,proto3" json:"waypoints,omitempty"`
	CompletionAction string                 `protobuf:"bytes,7,opt,name=completion_action,json=completionAction,proto3" json:"completion_action,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *MissionExecutionEnvelope) Reset() {
	*x = MissionExecutionEnvelope{}
	mi := &file_atlas_vehicle_agent_channel_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MissionExecutionEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MissionExecutionEnvelope) ProtoMessage() {}

func (x *MissionExecutionEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_atlas_vehicle_agent_channel_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MissionExecutionEnvelope.ProtoReflect.Descriptor instead.
func (*MissionExecutionEnvelope) Descriptor() ([]byte, []int) {
	return file_atlas_vehicle_agent_channel_proto_rawDescGZIP(), []int{7}
}

func (x *MissionExecutionEnvelope) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

func (x *MissionExecutionEnvelope) GetMissionId() string {
	if x != nil {
		return x.MissionId
	}
	return ""
}

func (x *MissionExecutionEnvelope) GetDroneId() string {
	if x != nil {
		return x.DroneId
	}
	return ""
}

func (x *MissionExecutionEnvelope) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *MissionExecutionEnvelope) GetRequestedBy() string {
	if x != nil {
		return x.RequestedBy
	}
	return ""
}

func (x *MissionExecutionEnvelope) GetWaypoints() []*MissionWaypoint {
	if x != nil {
		return x.Waypoints
	}
	return nil
}

func (x *MissionExecutionEnvelope) GetCompletionAction() string {
	if x != nil {
		return x.CompletionAction
	}
	return ""
}

type MissionWaypoint struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Sequence          int32                  `protobuf:"varint,1,opt,name=sequence,proto3" json:"sequence,omitempty"`
	Latitude          float64                `protobuf:"fixed64,2,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude         float64                `protobuf:"fixed64,3,opt,name=longitude,proto3" json:"longitude,omitempty"`
	RelativeAltitudeM float64                `protobuf:"fixed64,4,opt,name=relative_altitude_m,json=relativeAltitudeM,proto3" json:"relative_altitude_m,omitempty"`
	SpeedMps          *float64               `protobuf:"fixed64,5,opt,name=speed_mps,json=speedMps,proto3,oneof" json:"speed_mps,omitempty"`
	LoiterTimeS       *float64               `protobuf:"fixed64,6,opt,name=loiter_time_s,json=loiterTimeS,proto3,oneof" json:"loiter_time_s,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *MissionWaypoint) Reset() {
	*x = MissionWaypoint{}
	mi := &file_atlas_vehicle_agent_channel_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MissionWaypoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MissionWaypoint) ProtoMessage() {}

func (x *MissionWaypoint) ProtoReflect() protoreflect.Message {
	mi := &file_atlas_vehicle_agent_channel_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MissionWaypoint.ProtoReflect.Descriptor instead.
func (*MissionWaypoint) Descriptor() ([]byte, []int) {
	return file_atlas_vehicle_agent_channel_proto_rawDescGZIP(), []int{8}
}

func (x *MissionWaypoint) GetSequence() int32 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *MissionWaypoint) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *MissionWaypoint) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *MissionWaypoint) GetRelativeAltitudeM() float64 {
	if x != nil {
		return x.RelativeAltitudeM
	}
	return 0
}

func (x *MissionWaypoint) GetSpeedMps() float64 {
	if x != nil && x.SpeedMps != nil {
		return *x.SpeedMps
	}
	return 0
}

func (x *MissionWaypoint) GetLoiterTimeS() float64 {
	if x != nil && x.LoiterTimeS != nil {
		return *x.LoiterTimeS
	}
	return 0
}

type MissionExecutionStatus struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ExecutionId        string                 `protobuf:"bytes,1,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	State              string                 `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	ResultMessage      string                 `protobuf:"bytes,3,opt,name=result_message,json=resultMessage,proto3" json:"result_message,omitempty"`
	CurrentMissionItem int32                  `protobuf:"varint,4,opt,name=current_mission_item,json=currentMissionItem,proto3" json:"current_mission_item,omitempty"`
	TotalMissionItems  int32                  `protobuf:"varint,5,opt,name=total_mission_items,json=totalMissionItems,proto3" json:"total_mission_items,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *MissionExecutionStatus) Reset() {
	*x = MissionExecutionStatus{}
	mi := &file_atlas_vehicle_agent_channel_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MissionExecutionStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MissionExecutionStatus) ProtoMessage() {}

func (x *MissionExecutionStatus) ProtoReflect() protoreflect.Message {
	mi := &file_atlas_vehicle_agent_channel_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MissionExecutionStatus.ProtoReflect.Descriptor instead.
func (*MissionExecutionStatus) Descriptor() ([]byte, []int) {
	return file_atlas_vehicle_agent_channel_proto_rawDescGZIP(), []int{9}
}

func (x *MissionExecutionStatus) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

func (x *MissionExecutionStatus) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *MissionExecutionStatus) GetResultMessage() string {
	if x != nil {
		return x.ResultMessage
	}
	return ""
}

func (x *MissionExecutionStatus) GetCurrentMissionItem() int32 {
	if x != nil {
		return x.CurrentMissionItem
	}
	return 0
}

func (x *MissionExecutionStatus) GetTotalMissionItems() int32 {
	if x != nil {
		return x.TotalMissionItems
	}
	return 0
}

type Ping struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nonce         string                 `protobuf:"bytes,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ping) Reset() {
	*x = Ping{}
	mi := &file_atlas_vehicle_agent_channel_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ping) ProtoMessage() {}

func (x *Ping) ProtoReflect() protoreflect.Message {
	mi := &file_atlas_vehicle_agent_channel_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ping.ProtoReflect.Descriptor instead.
func (*Ping) Descriptor() ([]byte, []int) {
	return file_atlas_vehicle_agent_channel_proto_rawDescGZIP(), []int{10}
}

func (x *Ping) GetNonce() string {
	if x != nil {
		return x.Nonce
	}
	return ""
}

var File_atlas_vehicle_agent_channel_proto protoreflect.FileDescriptor

const file_atlas_vehicle_agent_channel_proto_rawDesc = "" +
	"\n" +
	"!atlas/vehicle_agent_channel.proto\x12\x1catlas.vehicleagentchannel.v1\"\xef\x03\n" +
	"\x15VehicleAgentToBackend\x12(\n" +
	"\x10vehicle_agent_id\x18\x01 \x01(\tR\x0evehicleAgentId\x12G\n" +
	"\x05hello\x18\x02 \x01(\v2/.atlas.vehicleagentchannel.v1.VehicleAgentHelloH\x00R\x05hello\x12T\n" +
	"\x0ecommand_status\x18\x03 \x01(\v2+.atlas.vehicleagentchannel.v1.CommandStatusH\x00R\rcommandStatus\x12G\n" +
	"\theartbeat\x18\x04 \x01(\v2'.atlas.vehicleagentchannel.v1.HeartbeatH\x00R\theartbeat\x12G\n" +
	"\ttelemetry\x18\x05 \x01(\v2'.atlas.vehicleagentchannel.v1.TelemetryH\x00R\ttelemetry\x12p\n" +
	"\x18mission_execution_status\x18\x06 \x01(\v24.atlas.vehicleagentchannel.v1.MissionExecutionStatusH\x00R\x16missionExecutionStatusB\t\n" +
	"\apayload\"\x8e\x02\n" +
	"\x15BackendToVehicleAgent\x12I\n" +
	"\acommand\x18\x01 \x01(\v2-.atlas.vehicleagentchannel.v1.CommandEnvelopeH\x00R\acommand\x128\n" +
	"\x04ping\x18\x02 \x01(\v2\".atlas.vehicleagentchannel.v1.PingH\x00R\x04ping\x12e\n" +
	"\x11mission_execution\x18\x03 \x01(\v26.atlas.vehicleagentchannel.v1.MissionExecutionEnvelopeH\x00R\x10missionExecutionB\t\n" +
	"\apayload\"\x81\x01\n" +
	"\x11VehicleAgentHello\x12\x19\n" +
	"\bdrone_id\x18\x01 \x01(\tR\adroneId\x122\n" +
	"\x15vehicle_agent_version\x18\x02 \x01(\tR\x13vehicleAgentVersion\x12\x1d\n" +
	"\n" +
	"drone_name\x18\x03 \x01(\tR\tdroneName\"?\n" +
	"\tHeartbeat\x122\n" +
	"\x15vehicle_agent_version\x18\x01 \x01(\tR\x13vehicleAgentVersion\"\xe4\x03\n" +
	"\tTelemetry\x12\x1f\n" +
	"\vobserved_at\x18\x01 \x01(\tR\n" +
	"observedAt\x12'\n" +
	"\x0fbattery_percent\x18\x02 \x01(\x01R\x0ebatteryPercent\x12.\n" +
	"\x13relative_altitude_m\x18\x03 \x01(\x01R\x11relativeAltitudeM\x12\x1f\n" +
	"\vflight_mode\x18\x04 \x01(\tR\n" +
	"flightMode\x12\x14\n" +
	"\x05armed\x18\x05 \x01(\bR\x05armed\x12\x15\n" +
	"\x06in_air\x18\x06 \x01(\bR\x05inAir\x12\x1a\n" +
	"\blatitude\x18\a \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\b \x01(\x01R\tlongitude\x12\x1f\n" +
	"\vheading_deg\x18\t \x01(\x01R\n" +
	"headingDeg\x12\x17\n" +
	"\agps_fix\x18\n" +
	" \x01(\tR\x06gpsFix\x12-\n" +
	"\x12satellites_visible\x18\v \x01(\x05R\x11satellitesVisible\x12*\n" +
	"\x11home_position_set\x18\f \x01(\bR\x0fhomePositionSet\x12\x16\n" +
	"\x06source\x18\r \x01(\tR\x06source\x12(\n" +
	"\x10ground_speed_mps\x18\x0e \x01(\x01R\x0egroundSpeedMps\"\x91\x01\n" +
	"\x0fCommandEnvelope\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x12\x19\n" +
	"\bdrone_id\x18\x02 \x01(\tR\adroneId\x12!\n" +
	"\fcommand_type\x18\x03 \x01(\tR\vcommandType\x12!\n" +
	"\frequested_by\x18\x04 \x01(\tR\vrequestedBy\"k\n" +
	"\rCommandStatus\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x12\x14\n" +
	"\x05state\x18\x02 \x01(\tR\x05state\x12%\n" +
	"\x0eresult_message\x18\x03 \x01(\tR\rresultMessage\"\xac\x02\n" +
	"\x18MissionExecutionEnvelope\x12!\n" +
	"\fexecution_id\x18\x01 \x01(\tR\vexecutionId\x12\x1d\n" +
	"\n" +
	"mission_id\x18\x02 \x01(\tR\tmissionId\x12\x19\n" +
	"\bdrone_id\x18\x03 \x01(\tR\adroneId\x12\x16\n" +
	"\x06action\x18\x04 \x01(\tR\x06action\x12!\n" +
	"\frequested_by\x18\x05 \x01(\tR\vrequestedBy\x12K\n" +
	"\twaypoints\x18\x06 \x03(\v2-.atlas.vehicleagentchannel.v1.MissionWaypointR\twaypoints\x12+\n" +
	"\x11completion_action\x18\a \x01(\tR\x10completionAction\"\x82\x02\n" +
	"\x0fMissionWaypoint\x12\x1a\n" +
	"\bsequence\x18\x01 \x01(\x05R\bsequence\x12\x1a\n" +
	"\blatitude\x18\x02 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x03 \x01(\x01R\tlongitude\x12.\n" +
	"\x13relative_altitude_m\x18\x04 \x01(\x01R\x11relativeAltitudeM\x12 \n" +
	"\tspeed_mps\x18\x05 \x01(\x01H\x00R\bspeedMps\x88\x01\x01\x12'\n" +
	"\rloiter_time_s\x18\x06 \x01(\x01H\x01R\vloiterTimeS\x88\x01\x01B\f\n" +
	"\n" +
	"_speed_mpsB\x10\n" +
	"\x0e_loiter_time_s\"\xda\x01\n" +
	"\x16MissionExecutionStatus\x12!\n" +
	"\fexecution_id\x18\x01 \x01(\tR\vexecutionId\x12\x14\n" +
	"\x05state\x18\x02 \x01(\tR\x05state\x12%\n" +
	"\x0eresult_message\x18\x03 \x01(\tR\rresultMessage\x120\n" +
	"\x14current_mission_item\x18\x04 \x01(\x05R\x12currentMissionItem\x12.\n" +
	"\x13total_mission_items\x18\x05 \x01(\x05R\x11totalMissionItems\"\x1c\n" +
	"\x04Ping\x12\x14\n" +
	"\x05nonce\x18\x01 \x01(\tR\x05nonce2\x95\x01\n" +
	"\x1aVehicleAgentChannelService\x12w\n" +
	"\aConnect\x123.atlas.vehicleagentchannel.v1.VehicleAgentToBackend\x1a3.atlas.vehicleagentchannel.v1.BackendToVehicleAgent(\x010\x01BTZRgithub.com/sunnyside/atlas/atlas-proto/vehicleagentchannelpb;vehicleagentchannelpbb\x06proto3"

var (
	file_atlas_vehicle_agent_channel_proto_rawDescOnce sync.Once
	file_atlas_vehicle_agent_channel_proto_rawDescData []byte
)

func file_atlas_vehicle_agent_channel_proto_rawDescGZIP() []byte {
	file_atlas_vehicle_agent_channel_proto_rawDescOnce.Do(func() {
		file_atlas_vehicle_agent_channel_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_atlas_vehicle_agent_channel_proto_rawDesc), len(file_atlas_vehicle_agent_channel_proto_rawDesc)))
	})
	return file_atlas_vehicle_agent_channel_proto_rawDescData
}

var file_atlas_vehicle_agent_channel_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_atlas_vehicle_agent_channel_proto_goTypes = []any{
	(*VehicleAgentToBackend)(nil),    // 0: atlas.vehicleagentchannel.v1.VehicleAgentToBackend
	(*BackendToVehicleAgent)(nil),    // 1: atlas.vehicleagentchannel.v1.BackendToVehicleAgent
	(*VehicleAgentHello)(nil),        // 2: atlas.vehicleagentchannel.v1.VehicleAgentHello
	(*Heartbeat)(nil),                // 3: atlas.vehicleagentchannel.v1.Heartbeat
	(*Telemetry)(nil),                // 4: atlas.vehicleagentchannel.v1.Telemetry
	(*CommandEnvelope)(nil),          // 5: atlas.vehicleagentchannel.v1.CommandEnvelope
	(*CommandStatus)(nil),            // 6: atlas.vehicleagentchannel.v1.CommandStatus
	(*MissionExecutionEnvelope)(nil), // 7: atlas.vehicleagentchannel.v1.MissionExecutionEnvelope
	(*MissionWaypoint)(nil),          // 8: atlas.vehicleagentchannel.v1.MissionWaypoint
	(*MissionExecutionStatus)(nil),   // 9: atlas.vehicleagentchannel.v1.MissionExecutionStatus
	(*Ping)(nil),                     // 10: atlas.vehicleagentchannel.v1.Ping
}
var file_atlas_vehicle_agent_channel_proto_depIdxs = []int32{
	2,  // 0: atlas.vehicleagentchannel.v1.VehicleAgentToBackend.hello:type_name -> atlas.vehicleagentchannel.v1.VehicleAgentHello
	6,  // 1: atlas.vehicleagentchannel.v1.VehicleAgentToBackend.command_status:type_name -> atlas.vehicleagentchannel.v1.CommandStatus
	3,  // 2: atlas.vehicleagentchannel.v1.VehicleAgentToBackend.heartbeat:type_name -> atlas.vehicleagentchannel.v1.Heartbeat
	4,  // 3: atlas.vehicleagentchannel.v1.VehicleAgentToBackend.telemetry:type_name -> atlas.vehicleagentchannel.v1.Telemetry
	9,  // 4: atlas.vehicleagentchannel.v1.VehicleAgentToBackend.mission_execution_status:type_name -> atlas.vehicleagentchannel.v1.MissionExecutionStatus
	5,  // 5: atlas.vehicleagentchannel.v1.BackendToVehicleAgent.command:type_name -> atlas.vehicleagentchannel.v1.CommandEnvelope
	10, // 6: atlas.vehicleagentchannel.v1.BackendToVehicleAgent.ping:type_name -> atlas.vehicleagentchannel.v1.Ping
	7,  // 7: atlas.vehicleagentchannel.v1.BackendToVehicleAgent.mission_execution:type_name -> atlas.vehicleagentchannel.v1.MissionExecutionEnvelope
	8,  // 8: atlas.vehicleagentchannel.v1.MissionExecutionEnvelope.waypoints:type_name -> atlas.vehicleagentchannel.v1.MissionWaypoint
	0,  // 9: atlas.vehicleagentchannel.v1.VehicleAgentChannelService.Connect:input_type -> atlas.vehicleagentchannel.v1.VehicleAgentToBackend
	1,  // 10: atlas.vehicleagentchannel.v1.VehicleAgentChannelService.Connect:output_type -> atlas.vehicleagentchannel.v1.BackendToVehicleAgent
	10, // [10:11] is the sub-list for method output_type
	9,  // [9:10] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_atlas_vehicle_agent_channel_proto_init() }
func file_atlas_vehicle_agent_channel_proto_init() {
	if File_atlas_vehicle_agent_channel_proto != nil {
		return
	}
	file_atlas_vehicle_agent_channel_proto_msgTypes[0].OneofWrappers = []any{
		(*VehicleAgentToBackend_Hello)(nil),
		(*VehicleAgentToBackend_CommandStatus)(nil),
		(*VehicleAgentToBackend_Heartbeat)(nil),
		(*VehicleAgentToBackend_Telemetry)(nil),
		(*VehicleAgentToBackend_MissionExecutionStatus)(nil),
	}
	file_atlas_vehicle_agent_channel_proto_msgTypes[1].OneofWrappers = []any{
		(*BackendToVehicleAgent_Command)(nil),
		(*BackendToVehicleAgent_Ping)(nil),
		(*BackendToVehicleAgent_MissionExecution)(nil),
	}
	file_atlas_vehicle_agent_channel_proto_msgTypes[8].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_atlas_vehicle_agent_channel_proto_rawDesc), len(file_atlas_vehicle_agent_channel_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_atlas_vehicle_agent_channel_proto_goTypes,
		DependencyIndexes: file_atlas_vehicle_agent_channel_proto_depIdxs,
		MessageInfos:      file_atlas_vehicle_agent_channel_proto_msgTypes,
	}.Build()
	File_atlas_vehicle_agent_channel_proto = out.File
	file_atlas_vehicle_agent_channel_proto_goTypes = nil
	file_atlas_vehicle_agent_channel_proto_depIdxs = nil
}
