// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v7.35.0
// source: atlas/vehicle_agent_channel.proto

package vehicleagentchannelpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	VehicleAgentChannelService_Connect_FullMethodName = "/atlas.vehicleagentchannel.v1.VehicleAgentChannelService/Connect"
)

// VehicleAgentChannelServiceClient is the client API for VehicleAgentChannelService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VehicleAgentChannelServiceClient interface {
	Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[VehicleAgentToBackend, BackendToVehicleAgent], error)
}

type vehicleAgentChannelServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewVehicleAgentChannelServiceClient(cc grpc.ClientConnInterface) VehicleAgentChannelServiceClient {
	return &vehicleAgentChannelServiceClient{cc}
}

func (c *vehicleAgentChannelServiceClient) Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[VehicleAgentToBackend, BackendToVehicleAgent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &VehicleAgentChannelService_ServiceDesc.Streams[0], VehicleAgentChannelService_Connect_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[VehicleAgentToBackend, BackendToVehicleAgent]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type VehicleAgentChannelService_ConnectClient = grpc.BidiStreamingClient[VehicleAgentToBackend, BackendToVehicleAgent]

// VehicleAgentChannelServiceServer is the server API for VehicleAgentChannelService service.
// All implementations must embed UnimplementedVehicleAgentChannelServiceServer
// for forward compatibility.
type VehicleAgentChannelServiceServer interface {
	Connect(grpc.BidiStreamingServer[VehicleAgentToBackend, BackendToVehicleAgent]) error
	mustEmbedUnimplementedVehicleAgentChannelServiceServer()
}

// UnimplementedVehicleAgentChannelServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedVehicleAgentChannelServiceServer struct{}

func (UnimplementedVehicleAgentChannelServiceServer) Connect(grpc.BidiStreamingServer[VehicleAgentToBackend, BackendToVehicleAgent]) error {
	return status.Errorf(codes.Unimplemented, "method Connect not implemented")
}
func (UnimplementedVehicleAgentChannelServiceServer) mustEmbedUnimplementedVehicleAgentChannelServiceServer() {
}
func (UnimplementedVehicleAgentChannelServiceServer) testEmbeddedByValue() {}

// UnsafeVehicleAgentChannelServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VehicleAgentChannelServiceServer will
// result in compilation errors.
type UnsafeVehicleAgentChannelServiceServer interface {
	mustEmbedUnimplementedVehicleAgentChannelServiceServer()
}

func RegisterVehicleAgentChannelServiceServer(s grpc.ServiceRegistrar, srv VehicleAgentChannelServiceServer) {
	// If the following call pancis, it indicates UnimplementedVehicleAgentChannelServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&VehicleAgentChannelService_ServiceDesc, srv)
}

func _VehicleAgentChannelService_Connect_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(VehicleAgentChannelServiceServer).Connect(&grpc.GenericServerStream[VehicleAgentToBackend, BackendToVehicleAgent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type VehicleAgentChannelService_ConnectServer = grpc.BidiStreamingServer[VehicleAgentToBackend, BackendToVehicleAgent]

// VehicleAgentChannelService_ServiceDesc is the grpc.ServiceDesc for VehicleAgentChannelService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VehicleAgentChannelService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "atlas.vehicleagentchannel.v1.VehicleAgentChannelService",
	HandlerType: (*VehicleAgentChannelServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Connect",
			Handler:       _VehicleAgentChannelService_Connect_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "atlas/vehicle_agent_channel.proto",
}
