export type EvidenceAssetStatus = "PENDING" | "READY" | "FAILED";
export type EvidenceAssetType = "STILL" | "EVENT_CLIP";

export type EvidenceAsset = {
  id: string;
  assetType: EvidenceAssetType;
  status: EvidenceAssetStatus;
  sourceId: string;
  droneId: string;
  droneName: string;
  incidentId?: string;
  missionId?: string;
  missionRunId?: string;
  recordingSessionId?: string;
  selectionId?: string;
  trackSessionId?: string;
  trackId?: string;
  trackClassLabel?: string;
  evidenceMarkerAnnotationId?: string;
  capturedAtUnixMs: number;
  sourceStartedAtUnixMs?: number;
  sourceEndedAtUnixMs?: number;
  requestedStartAtUnixMs?: number;
  requestedEndAtUnixMs?: number;
  relativePath: string;
  thumbnailRelativePath: string;
  mimeType: string;
  thumbnailMimeType: string;
  byteLength: number;
  sha256: string;
  thumbnailByteLength: number;
  thumbnailSha256: string;
  createdBy: string;
  createdAtUnixMs: number;
  updatedAtUnixMs: number;
  errorMessage: string;
};
