// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v7.35.0
// source: atlas/agent_channel.proto

package agentchannelpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AgentChannelService_Connect_FullMethodName = "/atlas.agentchannel.v1.AgentChannelService/Connect"
)

// AgentChannelServiceClient is the client API for AgentChannelService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AgentChannelServiceClient interface {
	Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AgentToBackend, BackendToAgent], error)
}

type agentChannelServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentChannelServiceClient(cc grpc.ClientConnInterface) AgentChannelServiceClient {
	return &agentChannelServiceClient{cc}
}

func (c *agentChannelServiceClient) Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AgentToBackend, BackendToAgent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AgentChannelService_ServiceDesc.Streams[0], AgentChannelService_Connect_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AgentToBackend, BackendToAgent]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentChannelService_ConnectClient = grpc.BidiStreamingClient[AgentToBackend, BackendToAgent]

// AgentChannelServiceServer is the server API for AgentChannelService service.
// All implementations must embed UnimplementedAgentChannelServiceServer
// for forward compatibility.
type AgentChannelServiceServer interface {
	Connect(grpc.BidiStreamingServer[AgentToBackend, BackendToAgent]) error
	mustEmbedUnimplementedAgentChannelServiceServer()
}

// UnimplementedAgentChannelServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentChannelServiceServer struct{}

func (UnimplementedAgentChannelServiceServer) Connect(grpc.BidiStreamingServer[AgentToBackend, BackendToAgent]) error {
	return status.Errorf(codes.Unimplemented, "method Connect not implemented")
}
func (UnimplementedAgentChannelServiceServer) mustEmbedUnimplementedAgentChannelServiceServer() {}
func (UnimplementedAgentChannelServiceServer) testEmbeddedByValue()                             {}

// UnsafeAgentChannelServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentChannelServiceServer will
// result in compilation errors.
type UnsafeAgentChannelServiceServer interface {
	mustEmbedUnimplementedAgentChannelServiceServer()
}

func RegisterAgentChannelServiceServer(s grpc.ServiceRegistrar, srv AgentChannelServiceServer) {
	// If the following call pancis, it indicates UnimplementedAgentChannelServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentChannelService_ServiceDesc, srv)
}

func _AgentChannelService_Connect_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AgentChannelServiceServer).Connect(&grpc.GenericServerStream[AgentToBackend, BackendToAgent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentChannelService_ConnectServer = grpc.BidiStreamingServer[AgentToBackend, BackendToAgent]

// AgentChannelService_ServiceDesc is the grpc.ServiceDesc for AgentChannelService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentChannelService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "atlas.agentchannel.v1.AgentChannelService",
	HandlerType: (*AgentChannelServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Connect",
			Handler:       _AgentChannelService_Connect_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "atlas/agent_channel.proto",
}
