// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: mavlink_direct/mavlink_direct.proto

package mavlink_direct

import (
	_ "github.com/sunnyside/atlas/atlas-agent/internal/mavsdkpb/mavsdk_options"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Possible results returned for action requests.
type MavlinkDirectResult_Result int32

const (
	MavlinkDirectResult_RESULT_UNKNOWN          MavlinkDirectResult_Result = 0 // Unknown result
	MavlinkDirectResult_RESULT_SUCCESS          MavlinkDirectResult_Result = 1 // Request succeeded
	MavlinkDirectResult_RESULT_ERROR            MavlinkDirectResult_Result = 2 // Error
	MavlinkDirectResult_RESULT_INVALID_MESSAGE  MavlinkDirectResult_Result = 3 // Invalid MAVLink message
	MavlinkDirectResult_RESULT_INVALID_FIELD    MavlinkDirectResult_Result = 4 // Invalid field name or value
	MavlinkDirectResult_RESULT_CONNECTION_ERROR MavlinkDirectResult_Result = 5 // Connection error
	MavlinkDirectResult_RESULT_NO_SYSTEM        MavlinkDirectResult_Result = 6 // No system connected
	MavlinkDirectResult_RESULT_TIMEOUT          MavlinkDirectResult_Result = 7 // Request timed out
)

// Enum value maps for MavlinkDirectResult_Result.
var (
	MavlinkDirectResult_Result_name = map[int32]string{
		0: "RESULT_UNKNOWN",
		1: "RESULT_SUCCESS",
		2: "RESULT_ERROR",
		3: "RESULT_INVALID_MESSAGE",
		4: "RESULT_INVALID_FIELD",
		5: "RESULT_CONNECTION_ERROR",
		6: "RESULT_NO_SYSTEM",
		7: "RESULT_TIMEOUT",
	}
	MavlinkDirectResult_Result_value = map[string]int32{
		"RESULT_UNKNOWN":          0,
		"RESULT_SUCCESS":          1,
		"RESULT_ERROR":            2,
		"RESULT_INVALID_MESSAGE":  3,
		"RESULT_INVALID_FIELD":    4,
		"RESULT_CONNECTION_ERROR": 5,
		"RESULT_NO_SYSTEM":        6,
		"RESULT_TIMEOUT":          7,
	}
)

func (x MavlinkDirectResult_Result) Enum() *MavlinkDirectResult_Result {
	p := new(MavlinkDirectResult_Result)
	*p = x
	return p
}

func (x MavlinkDirectResult_Result) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MavlinkDirectResult_Result) Descriptor() protoreflect.EnumDescriptor {
	return file_mavlink_direct_mavlink_direct_proto_enumTypes[0].Descriptor()
}

func (MavlinkDirectResult_Result) Type() protoreflect.EnumType {
	return &file_mavlink_direct_mavlink_direct_proto_enumTypes[0]
}

func (x MavlinkDirectResult_Result) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MavlinkDirectResult_Result.Descriptor instead.
func (MavlinkDirectResult_Result) EnumDescriptor() ([]byte, []int) {
	return file_mavlink_direct_mavlink_direct_proto_rawDescGZIP(), []int{7, 0}
}

type SendMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       *MavlinkMessage        `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"` // The MAVLink message to send
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageRequest) Reset() {
	*x = SendMessageRequest{}
	mi := &file_mavlink_direct_mavlink_direct_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageRequest) ProtoMessage() {}

func (x *SendMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mavlink_direct_mavlink_direct_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageRequest.ProtoReflect.Descriptor instead.
func (*SendMessageRequest) Descriptor() ([]byte, []int) {
	return file_mavlink_direct_mavlink_direct_proto_rawDescGZIP(), []int{0}
}

func (x *SendMessageRequest) GetMessage() *MavlinkMessage {
	if x != nil {
		return x.Message
	}
	return nil
}

type SendMessageResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	MavlinkDirectResult *MavlinkDirectResult   `protobuf:"bytes,1,opt,name=mavlink_direct_result,json=mavlinkDirectResult,proto3" json:"mavlink_direct_result,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *SendMessageResponse) Reset() {
	*x = SendMessageResponse{}
	mi := &file_mavlink_direct_mavlink_direct_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageResponse) ProtoMessage() {}

func (x *SendMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mavlink_direct_mavlink_direct_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageResponse.ProtoReflect.Descriptor instead.
func (*SendMessageResponse) Descriptor() ([]byte, []int) {
	return file_mavlink_direct_mavlink_direct_proto_rawDescGZIP(), []int{1}
}

func (x *SendMessageResponse) GetMavlinkDirectResult() *MavlinkDirectResult {
	if x != nil {
		return x.MavlinkDirectResult
	}
	return nil
}

type SubscribeMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageName   string                 `protobuf:"bytes,1,opt,name=message_name,json=messageName,proto3" json:"message_name,omitempty"` // MAVLink message name to filter for (e.g., "HEARTBEAT"), empty string = all messages
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeMessageRequest) Reset() {
	*x = SubscribeMessageRequest{}
	mi := &file_mavlink_direct_mavlink_direct_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeMessageRequest) ProtoMessage() {}

func (x *SubscribeMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mavlink_direct_mavlink_direct_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeMessageRequest.ProtoReflect.Descriptor instead.
func (*SubscribeMessageRequest) Descriptor() ([]byte, []int) {
	return file_mavlink_direct_mavlink_direct_proto_rawDescGZIP(), []int{2}
}

func (x *SubscribeMessageRequest) GetMessageName() string {
	if x != nil {
		return x.MessageName
	}
	return ""
}

type MessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       *MavlinkMessage        `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"` // The received MAVLink message
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageResponse) Reset() {
	*x = MessageResponse{}
	mi := &file_mavlink_direct_mavlink_direct_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageResponse) ProtoMessage() {}

func (x *MessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mavlink_direct_mavlink_direct_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageResponse.ProtoReflect.Descriptor instead.
func (*MessageResponse) Descriptor() ([]byte, []int) {
	return file_mavlink_direct_mavlink_direct_proto_rawDescGZIP(), []int{3}
}

func (x *MessageResponse) GetMessage() *MavlinkMessage {
	if x != nil {
		return x.Message
	}
	return nil
}

type LoadCustomXmlRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	XmlContent    string                 `protobuf:"bytes,1,opt,name=xml_content,json=xmlContent,proto3" json:"xml_content,omitempty"` // The custom MAVLink XML definition content
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadCustomXmlRequest) Reset() {
	*x = LoadCustomXmlRequest{}
	mi := &file_mavlink_direct_mavlink_direct_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadCustomXmlRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadCustomXmlRequest) ProtoMessage() {}

func (x *LoadCustomXmlRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mavlink_direct_mavlink_direct_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadCustomXmlRequest.ProtoReflect.Descriptor instead.
func (*LoadCustomXmlRequest) Descriptor() ([]byte, []int) {
	return file_mavlink_direct_mavlink_direct_proto_rawDescGZIP(), []int{4}
}

func (x *LoadCustomXmlRequest) GetXmlContent() string {
	if x != nil {
		return x.XmlContent
	}
	return ""
}

type LoadCustomXmlResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	MavlinkDirectResult *MavlinkDirectResult   `protobuf:"bytes,1,opt,name=mavlink_direct_result,json=mavlinkDirectResult,proto3" json:"mavlink_direct_result,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *LoadCustomXmlResponse) Reset() {
	*x = LoadCustomXmlResponse{}
	mi := &file_mavlink_direct_mavlink_direct_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadCustomXmlResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadCustomXmlResponse) ProtoMessage() {}

func (x *LoadCustomXmlResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mavlink_direct_mavlink_direct_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadCustomXmlResponse.ProtoReflect.Descriptor instead.
func (*LoadCustomXmlResponse) Descriptor() ([]byte, []int) {
	return file_mavlink_direct_mavlink_direct_proto_rawDescGZIP(), []int{5}
}

func (x *LoadCustomXmlResponse) GetMavlinkDirectResult() *MavlinkDirectResult {
	if x != nil {
		return x.MavlinkDirectResult
	}
	return nil
}

// A complete MAVLink message with all header information and fields
type MavlinkMessage struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	MessageName       string                 `protobuf:"bytes,1,opt,name=message_name,json=messageName,proto3" json:"message_name,omitempty"`                      // MAVLink message name (e.g., "HEARTBEAT", "GLOBAL_POSITION_INT")
	SystemId          uint32                 `protobuf:"varint,2,opt,name=system_id,json=systemId,proto3" json:"system_id,omitempty"`                              // System ID of the sender (for received messages)
	ComponentId       uint32                 `protobuf:"varint,3,opt,name=component_id,json=componentId,proto3" json:"component_id,omitempty"`                     // Component ID of the sender (for received messages)
	TargetSystemId    uint32                 `protobuf:"varint,4,opt,name=target_system_id,json=targetSystemId,proto3" json:"target_system_id,omitempty"`          // Target system ID (for sending, 0 for broadcast)
	TargetComponentId uint32                 `protobuf:"varint,5,opt,name=target_component_id,json=targetComponentId,proto3" json:"target_component_id,omitempty"` // Target component ID (for sending, 0 for broadcast)
	FieldsJson        string                 `protobuf:"bytes,6,opt,name=fields_json,json=fieldsJson,proto3" json:"fields_json,omitempty"`                         // All message fields as single JSON object
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *MavlinkMessage) Reset() {
	*x = MavlinkMessage{}
	mi := &file_mavlink_direct_mavlink_direct_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MavlinkMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MavlinkMessage) ProtoMessage() {}

func (x *MavlinkMessage) ProtoReflect() protoreflect.Message {
	mi := &file_mavlink_direct_mavlink_direct_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MavlinkMessage.ProtoReflect.Descriptor instead.
func (*MavlinkMessage) Descriptor() ([]byte, []int) {
	return file_mavlink_direct_mavlink_direct_proto_rawDescGZIP(), []int{6}
}

func (x *MavlinkMessage) GetMessageName() string {
	if x != nil {
		return x.MessageName
	}
	return ""
}

func (x *MavlinkMessage) GetSystemId() uint32 {
	if x != nil {
		return x.SystemId
	}
	return 0
}

func (x *MavlinkMessage) GetComponentId() uint32 {
	if x != nil {
		return x.ComponentId
	}
	return 0
}

func (x *MavlinkMessage) GetTargetSystemId() uint32 {
	if x != nil {
		return x.TargetSystemId
	}
	return 0
}

func (x *MavlinkMessage) GetTargetComponentId() uint32 {
	if x != nil {
		return x.TargetComponentId
	}
	return 0
}

func (x *MavlinkMessage) GetFieldsJson() string {
	if x != nil {
		return x.FieldsJson
	}
	return ""
}

// Result type.
type MavlinkDirectResult struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Result        MavlinkDirectResult_Result `protobuf:"varint,1,opt,name=result,proto3,enum=mavsdk.rpc.mavlink_direct.MavlinkDirectResult_Result" json:"result,omitempty"` // Result enum value
	ResultStr     string                     `protobuf:"bytes,2,opt,name=result_str,json=resultStr,proto3" json:"result_str,omitempty"`                                     // Human-readable English string describing the result
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MavlinkDirectResult) Reset() {
	*x = MavlinkDirectResult{}
	mi := &file_mavlink_direct_mavlink_direct_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MavlinkDirectResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MavlinkDirectResult) ProtoMessage() {}

func (x *MavlinkDirectResult) ProtoReflect() protoreflect.Message {
	mi := &file_mavlink_direct_mavlink_direct_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MavlinkDirectResult.ProtoReflect.Descriptor instead.
func (*MavlinkDirectResult) Descriptor() ([]byte, []int) {
	return file_mavlink_direct_mavlink_direct_proto_rawDescGZIP(), []int{7}
}

func (x *MavlinkDirectResult) GetResult() MavlinkDirectResult_Result {
	if x != nil {
		return x.Result
	}
	return MavlinkDirectResult_RESULT_UNKNOWN
}

func (x *MavlinkDirectResult) GetResultStr() string {
	if x != nil {
		return x.ResultStr
	}
	return ""
}

var File_mavlink_direct_mavlink_direct_proto protoreflect.FileDescriptor

const file_mavlink_direct_mavlink_direct_proto_rawDesc = "" +
	"\n" +
	"#mavlink_direct/mavlink_direct.proto\x12\x19mavsdk.rpc.mavlink_direct\x1a\x14mavsdk_options.proto\"Y\n" +
	"\x12SendMessageRequest\x12C\n" +
	"\amessage\x18\x01 \x01(\v2).mavsdk.rpc.mavlink_direct.MavlinkMessageR\amessage\"y\n" +
	"\x13SendMessageResponse\x12b\n" +
	"\x15mavlink_direct_result\x18\x01 \x01(\v2..mavsdk.rpc.mavlink_direct.MavlinkDirectResultR\x13mavlinkDirectResult\"<\n" +
	"\x17SubscribeMessageRequest\x12!\n" +
	"\fmessage_name\x18\x01 \x01(\tR\vmessageName\"V\n" +
	"\x0fMessageResponse\x12C\n" +
	"\amessage\x18\x01 \x01(\v2).mavsdk.rpc.mavlink_direct.MavlinkMessageR\amessage\"7\n" +
	"\x14LoadCustomXmlRequest\x12\x1f\n" +
	"\vxml_content\x18\x01 \x01(\tR\n" +
	"xmlContent\"{\n" +
	"\x15LoadCustomXmlResponse\x12b\n" +
	"\x15mavlink_direct_result\x18\x01 \x01(\v2..mavsdk.rpc.mavlink_direct.MavlinkDirectResultR\x13mavlinkDirectResult\"\xee\x01\n" +
	"\x0eMavlinkMessage\x12!\n" +
	"\fmessage_name\x18\x01 \x01(\tR\vmessageName\x12\x1b\n" +
	"\tsystem_id\x18\x02 \x01(\rR\bsystemId\x12!\n" +
	"\fcomponent_id\x18\x03 \x01(\rR\vcomponentId\x12(\n" +
	"\x10target_system_id\x18\x04 \x01(\rR\x0etargetSystemId\x12.\n" +
	"\x13target_component_id\x18\x05 \x01(\rR\x11targetComponentId\x12\x1f\n" +
	"\vfields_json\x18\x06 \x01(\tR\n" +
	"fieldsJson\"\xc5\x02\n" +
	"\x13MavlinkDirectResult\x12M\n" +
	"\x06result\x18\x01 \x01(\x0e25.mavsdk.rpc.mavlink_direct.MavlinkDirectResult.ResultR\x06result\x12\x1d\n" +
	"\n" +
	"result_str\x18\x02 \x01(\tR\tresultStr\"\xbf\x01\n" +
	"\x06Result\x12\x12\n" +
	"\x0eRESULT_UNKNOWN\x10\x00\x12\x12\n" +
	"\x0eRESULT_SUCCESS\x10\x01\x12\x10\n" +
	"\fRESULT_ERROR\x10\x02\x12\x1a\n" +
	"\x16RESULT_INVALID_MESSAGE\x10\x03\x12\x18\n" +
	"\x14RESULT_INVALID_FIELD\x10\x04\x12\x1b\n" +
	"\x17RESULT_CONNECTION_ERROR\x10\x05\x12\x14\n" +
	"\x10RESULT_NO_SYSTEM\x10\x06\x12\x12\n" +
	"\x0eRESULT_TIMEOUT\x10\a2\x80\x03\n" +
	"\x14MavlinkDirectService\x12r\n" +
	"\vSendMessage\x12-.mavsdk.rpc.mavlink_direct.SendMessageRequest\x1a..mavsdk.rpc.mavlink_direct.SendMessageResponse\"\x04\x80\xb5\x18\x01\x12z\n" +
	"\x10SubscribeMessage\x122.mavsdk.rpc.mavlink_direct.SubscribeMessageRequest\x1a*.mavsdk.rpc.mavlink_direct.MessageResponse\"\x04\x80\xb5\x18\x000\x01\x12x\n" +
	"\rLoadCustomXml\x12/.mavsdk.rpc.mavlink_direct.LoadCustomXmlRequest\x1a0.mavsdk.rpc.mavlink_direct.LoadCustomXmlResponse\"\x04\x80\xb5\x18\x01B.\n" +
	"\x18io.mavsdk.mavlink_directB\x12MavlinkDirectProtob\x06proto3"

var (
	file_mavlink_direct_mavlink_direct_proto_rawDescOnce sync.Once
	file_mavlink_direct_mavlink_direct_proto_rawDescData []byte
)

func file_mavlink_direct_mavlink_direct_proto_rawDescGZIP() []byte {
	file_mavlink_direct_mavlink_direct_proto_rawDescOnce.Do(func() {
		file_mavlink_direct_mavlink_direct_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mavlink_direct_mavlink_direct_proto_rawDesc), len(file_mavlink_direct_mavlink_direct_proto_rawDesc)))
	})
	return file_mavlink_direct_mavlink_direct_proto_rawDescData
}

var file_mavlink_direct_mavlink_direct_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_mavlink_direct_mavlink_direct_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_mavlink_direct_mavlink_direct_proto_goTypes = []any{
	(MavlinkDirectResult_Result)(0), // 0: mavsdk.rpc.mavlink_direct.MavlinkDirectResult.Result
	(*SendMessageRequest)(nil),      // 1: mavsdk.rpc.mavlink_direct.SendMessageRequest
	(*SendMessageResponse)(nil),     // 2: mavsdk.rpc.mavlink_direct.SendMessageResponse
	(*SubscribeMessageRequest)(nil), // 3: mavsdk.rpc.mavlink_direct.SubscribeMessageRequest
	(*MessageResponse)(nil),         // 4: mavsdk.rpc.mavlink_direct.MessageResponse
	(*LoadCustomXmlRequest)(nil),    // 5: mavsdk.rpc.mavlink_direct.LoadCustomXmlRequest
	(*LoadCustomXmlResponse)(nil),   // 6: mavsdk.rpc.mavlink_direct.LoadCustomXmlResponse
	(*MavlinkMessage)(nil),          // 7: mavsdk.rpc.mavlink_direct.MavlinkMessage
	(*MavlinkDirectResult)(nil),     // 8: mavsdk.rpc.mavlink_direct.MavlinkDirectResult
}
var file_mavlink_direct_mavlink_direct_proto_depIdxs = []int32{
	7, // 0: mavsdk.rpc.mavlink_direct.SendMessageRequest.message:type_name -> mavsdk.rpc.mavlink_direct.MavlinkMessage
	8, // 1: mavsdk.rpc.mavlink_direct.SendMessageResponse.mavlink_direct_result:type_name -> mavsdk.rpc.mavlink_direct.MavlinkDirectResult
	7, // 2: mavsdk.rpc.mavlink_direct.MessageResponse.message:type_name -> mavsdk.rpc.mavlink_direct.MavlinkMessage
	8, // 3: mavsdk.rpc.mavlink_direct.LoadCustomXmlResponse.mavlink_direct_result:type_name -> mavsdk.rpc.mavlink_direct.MavlinkDirectResult
	0, // 4: mavsdk.rpc.mavlink_direct.MavlinkDirectResult.result:type_name -> mavsdk.rpc.mavlink_direct.MavlinkDirectResult.Result
	1, // 5: mavsdk.rpc.mavlink_direct.MavlinkDirectService.SendMessage:input_type -> mavsdk.rpc.mavlink_direct.SendMessageRequest
	3, // 6: mavsdk.rpc.mavlink_direct.MavlinkDirectService.SubscribeMessage:input_type -> mavsdk.rpc.mavlink_direct.SubscribeMessageRequest
	5, // 7: mavsdk.rpc.mavlink_direct.MavlinkDirectService.LoadCustomXml:input_type -> mavsdk.rpc.mavlink_direct.LoadCustomXmlRequest
	2, // 8: mavsdk.rpc.mavlink_direct.MavlinkDirectService.SendMessage:output_type -> mavsdk.rpc.mavlink_direct.SendMessageResponse
	4, // 9: mavsdk.rpc.mavlink_direct.MavlinkDirectService.SubscribeMessage:output_type -> mavsdk.rpc.mavlink_direct.MessageResponse
	6, // 10: mavsdk.rpc.mavlink_direct.MavlinkDirectService.LoadCustomXml:output_type -> mavsdk.rpc.mavlink_direct.LoadCustomXmlResponse
	8, // [8:11] is the sub-list for method output_type
	5, // [5:8] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_mavlink_direct_mavlink_direct_proto_init() }
func file_mavlink_direct_mavlink_direct_proto_init() {
	if File_mavlink_direct_mavlink_direct_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mavlink_direct_mavlink_direct_proto_rawDesc), len(file_mavlink_direct_mavlink_direct_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_mavlink_direct_mavlink_direct_proto_goTypes,
		DependencyIndexes: file_mavlink_direct_mavlink_direct_proto_depIdxs,
		EnumInfos:         file_mavlink_direct_mavlink_direct_proto_enumTypes,
		MessageInfos:      file_mavlink_direct_mavlink_direct_proto_msgTypes,
	}.Build()
	File_mavlink_direct_mavlink_direct_proto = out.File
	file_mavlink_direct_mavlink_direct_proto_goTypes = nil
	file_mavlink_direct_mavlink_direct_proto_depIdxs = nil
}
