// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v7.35.0
// source: mavlink_direct/mavlink_direct.proto

package mavlink_direct

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MavlinkDirectService_SendMessage_FullMethodName      = "/mavsdk.rpc.mavlink_direct.MavlinkDirectService/SendMessage"
	MavlinkDirectService_SubscribeMessage_FullMethodName = "/mavsdk.rpc.mavlink_direct.MavlinkDirectService/SubscribeMessage"
	MavlinkDirectService_LoadCustomXml_FullMethodName    = "/mavsdk.rpc.mavlink_direct.MavlinkDirectService/LoadCustomXml"
)

// MavlinkDirectServiceClient is the client API for MavlinkDirectService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Enable direct MAVLink communication using libmav.
type MavlinkDirectServiceClient interface {
	// Send a MAVLink message directly to the system.
	//
	// This allows sending any MAVLink message with full control over the message content.
	SendMessage(ctx context.Context, in *SendMessageRequest, opts ...grpc.CallOption) (*SendMessageResponse, error)
	// Subscribe to incoming MAVLink messages.
	//
	// This provides direct access to incoming MAVLink messages. Use an empty string
	// in message_name to subscribe to all messages, or specify a message name
	// (e.g., "HEARTBEAT") to filter for specific message types.
	SubscribeMessage(ctx context.Context, in *SubscribeMessageRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[MessageResponse], error)
	// Load custom MAVLink message definitions from XML.
	//
	// This allows loading custom MAVLink message definitions at runtime,
	// extending the available message types beyond the built-in definitions.
	LoadCustomXml(ctx context.Context, in *LoadCustomXmlRequest, opts ...grpc.CallOption) (*LoadCustomXmlResponse, error)
}

type mavlinkDirectServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMavlinkDirectServiceClient(cc grpc.ClientConnInterface) MavlinkDirectServiceClient {
	return &mavlinkDirectServiceClient{cc}
}

func (c *mavlinkDirectServiceClient) SendMessage(ctx context.Context, in *SendMessageRequest, opts ...grpc.CallOption) (*SendMessageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendMessageResponse)
	err := c.cc.Invoke(ctx, MavlinkDirectService_SendMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mavlinkDirectServiceClient) SubscribeMessage(ctx context.Context, in *SubscribeMessageRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[MessageResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MavlinkDirectService_ServiceDesc.Streams[0], MavlinkDirectService_SubscribeMessage_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeMessageRequest, MessageResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MavlinkDirectService_SubscribeMessageClient = grpc.ServerStreamingClient[MessageResponse]

func (c *mavlinkDirectServiceClient) LoadCustomXml(ctx context.Context, in *LoadCustomXmlRequest, opts ...grpc.CallOption) (*LoadCustomXmlResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoadCustomXmlResponse)
	err := c.cc.Invoke(ctx, MavlinkDirectService_LoadCustomXml_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MavlinkDirectServiceServer is the server API for MavlinkDirectService service.
// All implementations must embed UnimplementedMavlinkDirectServiceServer
// for forward compatibility.
//
// Enable direct MAVLink communication using libmav.
type MavlinkDirectServiceServer interface {
	// Send a MAVLink message directly to the system.
	//
	// This allows sending any MAVLink message with full control over the message content.
	SendMessage(context.Context, *SendMessageRequest) (*SendMessageResponse, error)
	// Subscribe to incoming MAVLink messages.
	//
	// This provides direct access to incoming MAVLink messages. Use an empty string
	// in message_name to subscribe to all messages, or specify a message name
	// (e.g., "HEARTBEAT") to filter for specific message types.
	SubscribeMessage(*SubscribeMessageRequest, grpc.ServerStreamingServer[MessageResponse]) error
	// Load custom MAVLink message definitions from XML.
	//
	// This allows loading custom MAVLink message definitions at runtime,
	// extending the available message types beyond the built-in definitions.
	LoadCustomXml(context.Context, *LoadCustomXmlRequest) (*LoadCustomXmlResponse, error)
	mustEmbedUnimplementedMavlinkDirectServiceServer()
}

// UnimplementedMavlinkDirectServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMavlinkDirectServiceServer struct{}

func (UnimplementedMavlinkDirectServiceServer) SendMessage(context.Context, *SendMessageRequest) (*SendMessageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendMessage not implemented")
}
func (UnimplementedMavlinkDirectServiceServer) SubscribeMessage(*SubscribeMessageRequest, grpc.ServerStreamingServer[MessageResponse]) error {
	return status.Errorf(codes.Unimplemented, "method SubscribeMessage not implemented")
}
func (UnimplementedMavlinkDirectServiceServer) LoadCustomXml(context.Context, *LoadCustomXmlRequest) (*LoadCustomXmlResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoadCustomXml not implemented")
}
func (UnimplementedMavlinkDirectServiceServer) mustEmbedUnimplementedMavlinkDirectServiceServer() {}
func (UnimplementedMavlinkDirectServiceServer) testEmbeddedByValue()                              {}

// UnsafeMavlinkDirectServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MavlinkDirectServiceServer will
// result in compilation errors.
type UnsafeMavlinkDirectServiceServer interface {
	mustEmbedUnimplementedMavlinkDirectServiceServer()
}

func RegisterMavlinkDirectServiceServer(s grpc.ServiceRegistrar, srv MavlinkDirectServiceServer) {
	// If the following call pancis, it indicates UnimplementedMavlinkDirectServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MavlinkDirectService_ServiceDesc, srv)
}

func _MavlinkDirectService_SendMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MavlinkDirectServiceServer).SendMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MavlinkDirectService_SendMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MavlinkDirectServiceServer).SendMessage(ctx, req.(*SendMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MavlinkDirectService_SubscribeMessage_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeMessageRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MavlinkDirectServiceServer).SubscribeMessage(m, &grpc.GenericServerStream[SubscribeMessageRequest, MessageResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MavlinkDirectService_SubscribeMessageServer = grpc.ServerStreamingServer[MessageResponse]

func _MavlinkDirectService_LoadCustomXml_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoadCustomXmlRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MavlinkDirectServiceServer).LoadCustomXml(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MavlinkDirectService_LoadCustomXml_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MavlinkDirectServiceServer).LoadCustomXml(ctx, req.(*LoadCustomXmlRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MavlinkDirectService_ServiceDesc is the grpc.ServiceDesc for MavlinkDirectService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MavlinkDirectService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mavsdk.rpc.mavlink_direct.MavlinkDirectService",
	HandlerType: (*MavlinkDirectServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendMessage",
			Handler:    _MavlinkDirectService_SendMessage_Handler,
		},
		{
			MethodName: "LoadCustomXml",
			Handler:    _MavlinkDirectService_LoadCustomXml_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubscribeMessage",
			Handler:       _MavlinkDirectService_SubscribeMessage_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "mavlink_direct/mavlink_direct.proto",
}
