// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: mavsdk_options.proto

package mavsdk_options

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AsyncType int32

const (
	AsyncType_ASYNC AsyncType = 0
	AsyncType_SYNC  AsyncType = 1
	AsyncType_BOTH  AsyncType = 2
)

// Enum value maps for AsyncType.
var (
	AsyncType_name = map[int32]string{
		0: "ASYNC",
		1: "SYNC",
		2: "BOTH",
	}
	AsyncType_value = map[string]int32{
		"ASYNC": 0,
		"SYNC":  1,
		"BOTH":  2,
	}
)

func (x AsyncType) Enum() *AsyncType {
	p := new(AsyncType)
	*p = x
	return p
}

func (x AsyncType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AsyncType) Descriptor() protoreflect.EnumDescriptor {
	return file_mavsdk_options_proto_enumTypes[0].Descriptor()
}

func (AsyncType) Type() protoreflect.EnumType {
	return &file_mavsdk_options_proto_enumTypes[0]
}

func (x AsyncType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AsyncType.Descriptor instead.
func (AsyncType) EnumDescriptor() ([]byte, []int) {
	return file_mavsdk_options_proto_rawDescGZIP(), []int{0}
}

var file_mavsdk_options_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         50000,
		Name:          "mavsdk.options.default_value",
		Tag:           "bytes,50000,opt,name=default_value",
		Filename:      "mavsdk_options.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*float64)(nil),
		Field:         50001,
		Name:          "mavsdk.options.epsilon",
		Tag:           "fixed64,50001,opt,name=epsilon",
		Filename:      "mavsdk_options.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*AsyncType)(nil),
		Field:         50000,
		Name:          "mavsdk.options.async_type",
		Tag:           "varint,50000,opt,name=async_type,enum=mavsdk.options.AsyncType",
		Filename:      "mavsdk_options.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         50001,
		Name:          "mavsdk.options.is_finite",
		Tag:           "varint,50001,opt,name=is_finite",
		Filename:      "mavsdk_options.proto",
	},
}

// Extension fields to descriptorpb.FieldOptions.
var (
	// optional string default_value = 50000;
	E_DefaultValue = &file_mavsdk_options_proto_extTypes[0]
	// optional double epsilon = 50001;
	E_Epsilon = &file_mavsdk_options_proto_extTypes[1]
)

// Extension fields to descriptorpb.MethodOptions.
var (
	// optional mavsdk.options.AsyncType async_type = 50000;
	E_AsyncType = &file_mavsdk_options_proto_extTypes[2]
	// optional bool is_finite = 50001;
	E_IsFinite = &file_mavsdk_options_proto_extTypes[3]
)

var File_mavsdk_options_proto protoreflect.FileDescriptor

const file_mavsdk_options_proto_rawDesc = "" +
	"\n" +
	"\x14mavsdk_options.proto\x12\x0emavsdk.options\x1a google/protobuf/descriptor.proto**\n" +
	"\tAsyncType\x12\t\n" +
	"\x05ASYNC\x10\x00\x12\b\n" +
	"\x04SYNC\x10\x01\x12\b\n" +
	"\x04BOTH\x10\x02:D\n" +
	"\rdefault_value\x12\x1d.google.protobuf.FieldOptions\x18І\x03 \x01(\tR\fdefaultValue:9\n" +
	"\aepsilon\x12\x1d.google.protobuf.FieldOptions\x18ц\x03 \x01(\x01R\aepsilon:Z\n" +
	"\n" +
	"async_type\x12\x1e.google.protobuf.MethodOptions\x18І\x03 \x01(\x0e2\x19.mavsdk.options.AsyncTypeR\tasyncType:=\n" +
	"\tis_finite\x12\x1e.google.protobuf.MethodOptions\x18ц\x03 \x01(\bR\bisFiniteB\x10\n" +
	"\x0eoptions.mavsdkb\x06proto3"

var (
	file_mavsdk_options_proto_rawDescOnce sync.Once
	file_mavsdk_options_proto_rawDescData []byte
)

func file_mavsdk_options_proto_rawDescGZIP() []byte {
	file_mavsdk_options_proto_rawDescOnce.Do(func() {
		file_mavsdk_options_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mavsdk_options_proto_rawDesc), len(file_mavsdk_options_proto_rawDesc)))
	})
	return file_mavsdk_options_proto_rawDescData
}

var file_mavsdk_options_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_mavsdk_options_proto_goTypes = []any{
	(AsyncType)(0),                     // 0: mavsdk.options.AsyncType
	(*descriptorpb.FieldOptions)(nil),  // 1: google.protobuf.FieldOptions
	(*descriptorpb.MethodOptions)(nil), // 2: google.protobuf.MethodOptions
}
var file_mavsdk_options_proto_depIdxs = []int32{
	1, // 0: mavsdk.options.default_value:extendee -> google.protobuf.FieldOptions
	1, // 1: mavsdk.options.epsilon:extendee -> google.protobuf.FieldOptions
	2, // 2: mavsdk.options.async_type:extendee -> google.protobuf.MethodOptions
	2, // 3: mavsdk.options.is_finite:extendee -> google.protobuf.MethodOptions
	0, // 4: mavsdk.options.async_type:type_name -> mavsdk.options.AsyncType
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	4, // [4:5] is the sub-list for extension type_name
	0, // [0:4] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_mavsdk_options_proto_init() }
func file_mavsdk_options_proto_init() {
	if File_mavsdk_options_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mavsdk_options_proto_rawDesc), len(file_mavsdk_options_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 4,
			NumServices:   0,
		},
		GoTypes:           file_mavsdk_options_proto_goTypes,
		DependencyIndexes: file_mavsdk_options_proto_depIdxs,
		EnumInfos:         file_mavsdk_options_proto_enumTypes,
		ExtensionInfos:    file_mavsdk_options_proto_extTypes,
	}.Build()
	File_mavsdk_options_proto = out.File
	file_mavsdk_options_proto_goTypes = nil
	file_mavsdk_options_proto_depIdxs = nil
}
