// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v7.35.0
// source: atlas/ground_station.proto

package groundstationpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GroundStationService_OpenSession_FullMethodName          = "/atlas.groundstation.v1.GroundStationService/OpenSession"
	GroundStationService_OpenPerceptionStream_FullMethodName = "/atlas.groundstation.v1.GroundStationService/OpenPerceptionStream"
	GroundStationService_OpenSpatialStream_FullMethodName    = "/atlas.groundstation.v1.GroundStationService/OpenSpatialStream"
)

// GroundStationServiceClient is the client API for GroundStationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// GroundStationService is hosted by the native Atlas application. The onboard
// agent initiates this session and keeps reconnecting while the HM30 path is
// available. Registration must be the first message on every new session.
type GroundStationServiceClient interface {
	OpenSession(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AgentToGroundStation, GroundStationToAgent], error)
	// Perception is isolated from the command/telemetry session so high-rate
	// detection updates cannot delay safety-critical command acknowledgements.
	// The first message must register the perception stream against an active
	// agent session.
	OpenPerceptionStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AgentPerception, GroundStationPerception], error)
	// Spatial snapshots have their own stream because a complete 100,000-point
	// cloud is intentionally much larger than telemetry or perception metadata.
	// Congestion here must never delay command acknowledgements or heartbeats.
	OpenSpatialStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AgentSpatial, GroundStationSpatial], error)
}

type groundStationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGroundStationServiceClient(cc grpc.ClientConnInterface) GroundStationServiceClient {
	return &groundStationServiceClient{cc}
}

func (c *groundStationServiceClient) OpenSession(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AgentToGroundStation, GroundStationToAgent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &GroundStationService_ServiceDesc.Streams[0], GroundStationService_OpenSession_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AgentToGroundStation, GroundStationToAgent]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GroundStationService_OpenSessionClient = grpc.BidiStreamingClient[AgentToGroundStation, GroundStationToAgent]

func (c *groundStationServiceClient) OpenPerceptionStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AgentPerception, GroundStationPerception], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &GroundStationService_ServiceDesc.Streams[1], GroundStationService_OpenPerceptionStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AgentPerception, GroundStationPerception]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GroundStationService_OpenPerceptionStreamClient = grpc.BidiStreamingClient[AgentPerception, GroundStationPerception]

func (c *groundStationServiceClient) OpenSpatialStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AgentSpatial, GroundStationSpatial], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &GroundStationService_ServiceDesc.Streams[2], GroundStationService_OpenSpatialStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AgentSpatial, GroundStationSpatial]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GroundStationService_OpenSpatialStreamClient = grpc.BidiStreamingClient[AgentSpatial, GroundStationSpatial]

// GroundStationServiceServer is the server API for GroundStationService service.
// All implementations must embed UnimplementedGroundStationServiceServer
// for forward compatibility.
//
// GroundStationService is hosted by the native Atlas application. The onboard
// agent initiates this session and keeps reconnecting while the HM30 path is
// available. Registration must be the first message on every new session.
type GroundStationServiceServer interface {
	OpenSession(grpc.BidiStreamingServer[AgentToGroundStation, GroundStationToAgent]) error
	// Perception is isolated from the command/telemetry session so high-rate
	// detection updates cannot delay safety-critical command acknowledgements.
	// The first message must register the perception stream against an active
	// agent session.
	OpenPerceptionStream(grpc.BidiStreamingServer[AgentPerception, GroundStationPerception]) error
	// Spatial snapshots have their own stream because a complete 100,000-point
	// cloud is intentionally much larger than telemetry or perception metadata.
	// Congestion here must never delay command acknowledgements or heartbeats.
	OpenSpatialStream(grpc.BidiStreamingServer[AgentSpatial, GroundStationSpatial]) error
	mustEmbedUnimplementedGroundStationServiceServer()
}

// UnimplementedGroundStationServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGroundStationServiceServer struct{}

func (UnimplementedGroundStationServiceServer) OpenSession(grpc.BidiStreamingServer[AgentToGroundStation, GroundStationToAgent]) error {
	return status.Errorf(codes.Unimplemented, "method OpenSession not implemented")
}
func (UnimplementedGroundStationServiceServer) OpenPerceptionStream(grpc.BidiStreamingServer[AgentPerception, GroundStationPerception]) error {
	return status.Errorf(codes.Unimplemented, "method OpenPerceptionStream not implemented")
}
func (UnimplementedGroundStationServiceServer) OpenSpatialStream(grpc.BidiStreamingServer[AgentSpatial, GroundStationSpatial]) error {
	return status.Errorf(codes.Unimplemented, "method OpenSpatialStream not implemented")
}
func (UnimplementedGroundStationServiceServer) mustEmbedUnimplementedGroundStationServiceServer() {}
func (UnimplementedGroundStationServiceServer) testEmbeddedByValue()                              {}

// UnsafeGroundStationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GroundStationServiceServer will
// result in compilation errors.
type UnsafeGroundStationServiceServer interface {
	mustEmbedUnimplementedGroundStationServiceServer()
}

func RegisterGroundStationServiceServer(s grpc.ServiceRegistrar, srv GroundStationServiceServer) {
	// If the following call pancis, it indicates UnimplementedGroundStationServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GroundStationService_ServiceDesc, srv)
}

func _GroundStationService_OpenSession_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GroundStationServiceServer).OpenSession(&grpc.GenericServerStream[AgentToGroundStation, GroundStationToAgent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GroundStationService_OpenSessionServer = grpc.BidiStreamingServer[AgentToGroundStation, GroundStationToAgent]

func _GroundStationService_OpenPerceptionStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GroundStationServiceServer).OpenPerceptionStream(&grpc.GenericServerStream[AgentPerception, GroundStationPerception]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GroundStationService_OpenPerceptionStreamServer = grpc.BidiStreamingServer[AgentPerception, GroundStationPerception]

func _GroundStationService_OpenSpatialStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GroundStationServiceServer).OpenSpatialStream(&grpc.GenericServerStream[AgentSpatial, GroundStationSpatial]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GroundStationService_OpenSpatialStreamServer = grpc.BidiStreamingServer[AgentSpatial, GroundStationSpatial]

// GroundStationService_ServiceDesc is the grpc.ServiceDesc for GroundStationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GroundStationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "atlas.groundstation.v1.GroundStationService",
	HandlerType: (*GroundStationServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "OpenSession",
			Handler:       _GroundStationService_OpenSession_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "OpenPerceptionStream",
			Handler:       _GroundStationService_OpenPerceptionStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "OpenSpatialStream",
			Handler:       _GroundStationService_OpenSpatialStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "atlas/ground_station.proto",
}
