// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: action/action.proto

package action

import (
	_ "github.com/sunnyside/atlas/atlas-agent/internal/mavsdkpb/mavsdk_options"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Yaw behaviour during orbit flight.
type OrbitYawBehavior int32

const (
	OrbitYawBehavior_ORBIT_YAW_BEHAVIOR_HOLD_FRONT_TO_CIRCLE_CENTER  OrbitYawBehavior = 0 // Vehicle front points to the center (default)
	OrbitYawBehavior_ORBIT_YAW_BEHAVIOR_HOLD_INITIAL_HEADING         OrbitYawBehavior = 1 // Vehicle front holds heading when message received
	OrbitYawBehavior_ORBIT_YAW_BEHAVIOR_UNCONTROLLED                 OrbitYawBehavior = 2 // Yaw uncontrolled
	OrbitYawBehavior_ORBIT_YAW_BEHAVIOR_HOLD_FRONT_TANGENT_TO_CIRCLE OrbitYawBehavior = 3 // Vehicle front follows flight path (tangential to circle)
	OrbitYawBehavior_ORBIT_YAW_BEHAVIOR_RC_CONTROLLED                OrbitYawBehavior = 4 // Yaw controlled by RC input
)

// Enum value maps for OrbitYawBehavior.
var (
	OrbitYawBehavior_name = map[int32]string{
		0: "ORBIT_YAW_BEHAVIOR_HOLD_FRONT_TO_CIRCLE_CENTER",
		1: "ORBIT_YAW_BEHAVIOR_HOLD_INITIAL_HEADING",
		2: "ORBIT_YAW_BEHAVIOR_UNCONTROLLED",
		3: "ORBIT_YAW_BEHAVIOR_HOLD_FRONT_TANGENT_TO_CIRCLE",
		4: "ORBIT_YAW_BEHAVIOR_RC_CONTROLLED",
	}
	OrbitYawBehavior_value = map[string]int32{
		"ORBIT_YAW_BEHAVIOR_HOLD_FRONT_TO_CIRCLE_CENTER":  0,
		"ORBIT_YAW_BEHAVIOR_HOLD_INITIAL_HEADING":         1,
		"ORBIT_YAW_BEHAVIOR_UNCONTROLLED":                 2,
		"ORBIT_YAW_BEHAVIOR_HOLD_FRONT_TANGENT_TO_CIRCLE": 3,
		"ORBIT_YAW_BEHAVIOR_RC_CONTROLLED":                4,
	}
)

func (x OrbitYawBehavior) Enum() *OrbitYawBehavior {
	p := new(OrbitYawBehavior)
	*p = x
	return p
}

func (x OrbitYawBehavior) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrbitYawBehavior) Descriptor() protoreflect.EnumDescriptor {
	return file_action_action_proto_enumTypes[0].Descriptor()
}

func (OrbitYawBehavior) Type() protoreflect.EnumType {
	return &file_action_action_proto_enumTypes[0]
}

func (x OrbitYawBehavior) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrbitYawBehavior.Descriptor instead.
func (OrbitYawBehavior) EnumDescriptor() ([]byte, []int) {
	return file_action_action_proto_rawDescGZIP(), []int{0}
}

// Commanded values for relays
type RelayCommand int32

const (
	RelayCommand_RELAY_COMMAND_ON  RelayCommand = 0 // Turn the relay off
	RelayCommand_RELAY_COMMAND_OFF RelayCommand = 1 // Turn the relay on.
)

// Enum value maps for RelayCommand.
var (
	RelayCommand_name = map[int32]string{
		0: "RELAY_COMMAND_ON",
		1: "RELAY_COMMAND_OFF",
	}
	RelayCommand_value = map[string]int32{
		"RELAY_COMMAND_ON":  0,
		"RELAY_COMMAND_OFF": 1,
	}
)

func (x RelayCommand) Enum() *RelayCommand {
	p := new(RelayCommand)
	*p = x
	return p
}

func (x RelayCommand) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RelayCommand) Descriptor() protoreflect.EnumDescriptor {
	return file_action_action_proto_enumTypes[1].Descriptor()
}

func (RelayCommand) Type() protoreflect.EnumType {
	return &file_action_action_proto_enumTypes[1]
}

func (x RelayCommand) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RelayCommand.Descriptor instead.
func (RelayCommand) EnumDescriptor() ([]byte, []int) {
	return file_action_action_proto_rawDescGZIP(), []int{1}
}

// Possible results returned for action requests.
type ActionResult_Result int32

const (
	ActionResult_RESULT_UNKNOWN                             ActionResult_Result = 0  // Unknown result
	ActionResult_RESULT_SUCCESS                             ActionResult_Result = 1  // Request was successful
	ActionResult_RESULT_NO_SYSTEM                           ActionResult_Result = 2  // No system is connected
	ActionResult_RESULT_CONNECTION_ERROR                    ActionResult_Result = 3  // Connection error
	ActionResult_RESULT_BUSY                                ActionResult_Result = 4  // Vehicle is busy
	ActionResult_RESULT_COMMAND_DENIED                      ActionResult_Result = 5  // Command refused by vehicle
	ActionResult_RESULT_COMMAND_DENIED_LANDED_STATE_UNKNOWN ActionResult_Result = 6  // Command refused because landed state is unknown
	ActionResult_RESULT_COMMAND_DENIED_NOT_LANDED           ActionResult_Result = 7  // Command refused because vehicle not landed
	ActionResult_RESULT_TIMEOUT                             ActionResult_Result = 8  // Request timed out
	ActionResult_RESULT_VTOL_TRANSITION_SUPPORT_UNKNOWN     ActionResult_Result = 9  // Hybrid/VTOL transition support is unknown
	ActionResult_RESULT_NO_VTOL_TRANSITION_SUPPORT          ActionResult_Result = 10 // Vehicle does not support hybrid/VTOL transitions
	ActionResult_RESULT_PARAMETER_ERROR                     ActionResult_Result = 11 // Error getting or setting parameter
	ActionResult_RESULT_UNSUPPORTED                         ActionResult_Result = 12 // Action not supported
	ActionResult_RESULT_FAILED                              ActionResult_Result = 13 // Action failed
	ActionResult_RESULT_INVALID_ARGUMENT                    ActionResult_Result = 14 // Invalid argument
)

// Enum value maps for ActionResult_Result.
var (
	ActionResult_Result_name = map[int32]string{
		0:  "RESULT_UNKNOWN",
		1:  "RESULT_SUCCESS",
		2:  "RESULT_NO_SYSTEM",
		3:  "RESULT_CONNECTION_ERROR",
		4:  "RESULT_BUSY",
		5:  "RESULT_COMMAND_DENIED",
		6:  "RESULT_COMMAND_DENIED_LANDED_STATE_UNKNOWN",
		7:  "RESULT_COMMAND_DENIED_NOT_LANDED",
		8:  "RESULT_TIMEOUT",
		9:  "RESULT_VTOL_TRANSITION_SUPPORT_UNKNOWN",
		10: "RESULT_NO_VTOL_TRANSITION_SUPPORT",
		11: "RESULT_PARAMETER_ERROR",
		12: "RESULT_UNSUPPORTED",
		13: "RESULT_FAILED",
		14: "RESULT_INVALID_ARGUMENT",
	}
	ActionResult_Result_value = map[string]int32{
		"RESULT_UNKNOWN":                             0,
		"RESULT_SUCCESS":                             1,
		"RESULT_NO_SYSTEM":                           2,
		"RESULT_CONNECTION_ERROR":                    3,
		"RESULT_BUSY":                                4,
		"RESULT_COMMAND_DENIED":                      5,
		"RESULT_COMMAND_DENIED_LANDED_STATE_UNKNOWN": 6,
		"RESULT_COMMAND_DENIED_NOT_LANDED":           7,
		"RESULT_TIMEOUT":                             8,
		"RESULT_VTOL_TRANSITION_SUPPORT_UNKNOWN":     9,
		"RESULT_NO_VTOL_TRANSITION_SUPPORT":          10,
		"RESULT_PARAMETER_ERROR":                     11,
		"RESULT_UNSUPPORTED":                         12,
		"RESULT_FAILED":                              13,
		"RESULT_INVALID_ARGUMENT":                    14,
	}
)

func (x ActionResult_Result) Enum() *ActionResult_Result {
	p := new(ActionResult_Result)
	*p = x
	return p
}

func (x ActionResult_Result) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ActionResult_Result) Descriptor() protoreflect.EnumDescriptor {
	return file_action_action_proto_enumTypes[2].Descriptor()
}

func (ActionResult_Result) Type() protoreflect.EnumType {
	return &file_action_action_proto_enumTypes[2]
}

func (x ActionResult_Result) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ActionResult_Result.Descriptor instead.
func (ActionResult_Result) EnumDescriptor() ([]byte, []int) {
	return file_action_action_proto_rawDescGZIP(), []int{48, 0}
}

type ArmRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArmRequest) Reset() {
	*x = ArmRequest{}
	mi := &file_action_action_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArmRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArmRequest) ProtoMessage() {}

func (x *ArmRequest) ProtoReflect() protoreflect.Message {
	mi := &file_action_action_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArmRequest.ProtoReflect.Descriptor instead.
func (*ArmRequest) Descriptor() ([]byte, []int) {
	return file_action_action_proto_rawDescGZIP(), []int{0}
}

type ArmResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActionResult  *ActionResult          `protobuf:"bytes,1,opt,name=action_result,json=actionResult,proto3" json:"action_result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArmResponse) Reset() {
	*x = ArmResponse{}
	mi := &file_action_action_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArmResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArmResponse) ProtoMessage() {}

func (x *ArmResponse) ProtoReflect() protoreflect.Message {
	mi := &file_action_action_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArmResponse.ProtoReflect.Descriptor instead.
func (*ArmResponse) Descriptor() ([]byte, []int) {
	return file_action_action_proto_rawDescGZIP(), []int{1}
}

func (x *ArmResponse) GetActionResult() *ActionResult {
	if x != nil {
		return x.ActionResult
	}
	return nil
}

type ArmForceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArmForceRequest) Reset() {
	*x = ArmForceRequest{}
	mi := &file_action_action_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArmForceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArmForceRequest) ProtoMessage() {}

func (x *ArmForceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_action_action_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArmForceRequest.ProtoReflect.Descriptor instead.
func (*ArmForceRequest) Descriptor() ([]byte, []int) {
	return file_action_action_proto_rawDescGZIP(), []int{2}
}

type ArmForceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActionResult  *ActionResult          `protobuf:"bytes,1,opt,name=action_result,json=actionResult,proto3" json:"action_result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArmForceResponse) Reset() {
	*x = ArmForceResponse{}
	mi := &file_action_action_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArmForceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArmForceResponse) ProtoMessage() {}

func (x *ArmForceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_action_action_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArmForceResponse.ProtoReflect.Descriptor instead.
func (*ArmForceResponse) Descriptor() ([]byte, []int) {
	return file_action_action_proto_rawDescGZIP(), []int{3}
}

func (x *ArmForceResponse) GetActionResult() *ActionResult {
	if x != nil {
		return x.ActionResult
	}
	return nil
}

type DisarmRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisarmRequest) Reset() {
	*x = DisarmRequest{}
	mi := &file_action_action_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisarmRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisarmRequest) ProtoMessage() {}

func (x *DisarmRequest) ProtoReflect() protoreflect.Message {
	mi := &file_action_action_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisarmRequest.ProtoReflect.Descriptor instead.
func (*DisarmRequest) Descriptor() ([]byte, []int) {
	return file_action_action_proto_rawDescGZIP(), []int{4}
}

type DisarmResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActionResult  *ActionResult          `protobuf:"bytes,1,opt,name=action_result,json=actionResult,proto3" json:"action_result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisarmResponse) Reset() {
	*x = DisarmResponse{}
	mi := &file_action_action_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisarmResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisarmResponse) ProtoMessage() {}

func (x *DisarmResponse) ProtoReflect() protoreflect.Message {
	mi := &file_action_action_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisarmResponse.ProtoReflect.Descriptor instead.
func (*DisarmResponse) Descriptor() ([]byte, []int) {
	return file_action_action_proto_rawDescGZIP(), []int{5}
}

func (x *DisarmResponse) GetActionResult() *ActionResult {
	if x != nil {
		return x.ActionResult
	}
	return nil
}

type TakeoffRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TakeoffRequest) Reset() {
	*x = TakeoffRequest{}
	mi := &file_action_action_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TakeoffRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TakeoffRequest) ProtoMessage() {}

func (x *TakeoffRequest) ProtoReflect() protoreflect.Message {
	mi := &file_action_action_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TakeoffRequest.ProtoReflect.Descriptor instead.
func (*TakeoffRequest) Descriptor() ([]byte, []int) {
	return file_action_action_proto_rawDescGZIP(), []int{6}
}

type TakeoffResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActionResult  *ActionResult          `protobuf:"bytes,1,opt,name=action_result,json=actionResult,proto3" json:"action_result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TakeoffResponse) Reset() {
	*x = TakeoffResponse{}
	mi := &file_action_action_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TakeoffResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TakeoffResponse) ProtoMessage() {}

func (x *TakeoffResponse) ProtoReflect() protoreflect.Message {
	mi := &file_action_action_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TakeoffResponse.ProtoReflect.Descriptor instead.
func (*TakeoffResponse) Descriptor() ([]byte, []int) {
	return file_action_action_proto_rawDescGZIP(), []int{7}
}

func (x *TakeoffResponse) GetActionResult() *ActionResult {
	if x != nil {
		return x.ActionResult
	}
	return nil
}

type LandRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LandRequest) Reset() {
	*x = LandRequest{}
	mi := &file_action_action_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LandRequest) ProtoMessage() {}

func (x *LandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_action_action_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LandRequest.ProtoReflect.Descriptor instead.
func (*LandRequest) Descriptor() ([]byte, []int) {
	return file_action_action_proto_rawDescGZIP(), []int{8}
}

type LandResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActionResult  *ActionResult          `protobuf:"bytes,1,opt,name=action_result,json=actionResult,proto3" json:"action_result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LandResponse) Reset() {
	*x = LandResponse{}
	mi := &file_action_action_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LandResponse) ProtoMessage() {}

func (x *LandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_action_action_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LandResponse.ProtoReflect.Descriptor instead.
func (*LandResponse) Descriptor() ([]byte, []int) {
	return file_action_action_proto_rawDescGZIP(), []int{9}
}

func (x *LandResponse) GetActionResult() *ActionResult {
	if x != nil {
		return x.ActionResult
	}
	return nil
}

type RebootRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RebootRequest) Reset() {
	*x = RebootRequest{}
	mi := &file_action_action_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RebootRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RebootRequest) ProtoMessage() {}

func (x *RebootRequest) ProtoReflect() protoreflect.Message {
	mi := &file_action_action_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RebootRequest.ProtoReflect.Descriptor instead.
func (*RebootRequest) Descriptor() ([]byte, []int) {
	return file_action_action_proto_rawDescGZIP(), []int{10}
}

type RebootResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActionResult  *ActionResult          `protobuf:"bytes,1,opt,name=action_result,json=actionResult,proto3" json:"action_result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RebootResponse) Reset() {
	*x = RebootResponse{}
	mi := &file_action_action_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RebootResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RebootResponse) ProtoMessage() {}

func (x *RebootResponse) ProtoReflect() protoreflect.Message {
	mi := &file_action_action_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RebootResponse.ProtoReflect.Descriptor instead.
func (*RebootResponse) Descriptor() ([]byte, []int) {
	return file_action_action_proto_rawDescGZIP(), []int{11}
}

func (x *RebootResponse) GetActionResult() *ActionResult {
	if x != nil {
		return x.ActionResult
	}
	return nil
}

type ShutdownRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShutdownRequest) Reset() {
	*x = ShutdownRequest{}
	mi := &file_action_action_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShutdownRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownRequest) ProtoMessage() {}

func (x *ShutdownRequest) ProtoReflect() protoreflect.Message {
	mi := &file_action_action_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownRequest.ProtoReflect.Descriptor instead.
func (*ShutdownRequest) Descriptor() ([]byte, []int) {
	return file_action_action_proto_rawDescGZIP(), []int{12}
}

type ShutdownResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActionResult  *ActionResult          `protobuf:"bytes,1,opt,name=action_result,json=actionResult,proto3" json:"action_result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShutdownResponse) Reset() {
	*x = ShutdownResponse{}
	mi := &file_action_action_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShutdownResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownResponse) ProtoMessage() {}

func (x *ShutdownResponse) ProtoReflect() protoreflect.Message {
	mi := &file_action_action_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownResponse.ProtoReflect.Descriptor instead.
func (*ShutdownResponse) Descriptor() ([]byte, []int) {
	return file_action_action_proto_rawDescGZIP(), []int{13}
}

func (x *ShutdownResponse) GetActionResult() *ActionResult {
	if x != nil {
		return x.ActionResult
	}
	return nil
}

type TerminateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TerminateRequest) Reset() {
	*x = TerminateRequest{}
	mi := &file_action_action_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TerminateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TerminateRequest) ProtoMessage() {}

func (x *TerminateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_action_action_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TerminateRequest.ProtoReflect.Descriptor instead.
func (*TerminateRequest) Descriptor() ([]byte, []int) {
	return file_action_action_proto_rawDescGZIP(), []int{14}
}

type TerminateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActionResult  *ActionResult          `protobuf:"bytes,1,opt,name=action_result,json=actionResult,proto3" json:"action_result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TerminateResponse) Reset() {
	*x = TerminateResponse{}
	mi := &file_action_action_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TerminateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TerminateResponse) ProtoMessage() {}

func (x *TerminateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_action_action_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TerminateResponse.ProtoReflect.Descriptor instead.
func (*TerminateResponse) Descriptor() ([]byte, []int) {
	return file_action_action_proto_rawDescGZIP(), []int{15}
}

func (x *TerminateResponse) GetActionResult() *ActionResult {
	if x != nil {
		return x.ActionResult
	}
	return nil
}

type KillRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KillRequest) Reset() {
	*x = KillRequest{}
	mi := &file_action_action_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KillRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KillRequest) ProtoMessage() {}

func (x *KillRequest) ProtoReflect() protoreflect.Message {
	mi := &file_action_action_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KillRequest.ProtoReflect.Descriptor instead.
func (*KillRequest) Descriptor() ([]byte, []int) {
	return file_action_action_proto_rawDescGZIP(), []int{16}
}

type KillResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActionResult  *ActionResult          `protobuf:"bytes,1,opt,name=action_result,json=actionResult,proto3" json:"action_result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KillResponse) Reset() {
	*x = KillResponse{}
	mi := &file_action_action_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KillResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KillResponse) ProtoMessage() {}

func (x *KillResponse) ProtoReflect() protoreflect.Message {
	mi := &file_action_action_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KillResponse.ProtoReflect.Descriptor instead.
func (*KillResponse) Descriptor() ([]byte, []int) {
	return file_action_action_proto_rawDescGZIP(), []int{17}
}

func (x *KillResponse) GetActionResult() *ActionResult {
	if x != nil {
		return x.ActionResult
	}
	return nil
}

type ReturnToLaunchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReturnToLaunchRequest) Reset() {
	*x = ReturnToLaunchRequest{}
	mi := &file_action_action_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReturnToLaunchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReturnToLaunchRequest) ProtoMessage() {}

func (x *ReturnToLaunchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_action_action_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReturnToLaunchRequest.ProtoReflect.Descriptor instead.
func (*ReturnToLaunchRequest) Descriptor() ([]byte, []int) {
	return file_action_action_proto_rawDescGZIP(), []int{18}
}

type ReturnToLaunchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActionResult  *ActionResult          `protobuf:"bytes,1,opt,name=action_result,json=actionResult,proto3" json:"action_result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReturnToLaunchResponse) Reset() {
	*x = ReturnToLaunchResponse{}
	mi := &file_action_action_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReturnToLaunchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReturnToLaunchResponse) ProtoMessage() {}

func (x *ReturnToLaunchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_action_action_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReturnToLaunchResponse.ProtoReflect.Descriptor instead.
func (*ReturnToLaunchResponse) Descriptor() ([]byte, []int) {
	return file_action_action_proto_rawDescGZIP(), []int{19}
}

func (x *ReturnToLaunchResponse) GetActionResult() *ActionResult {
	if x != nil {
		return x.ActionResult
	}
	return nil
}

type GotoLocationRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	LatitudeDeg       float64                `protobuf:"fixed64,1,opt,name=latitude_deg,json=latitudeDeg,proto3" json:"latitude_deg,omitempty"`                     // Latitude (in degrees)
	LongitudeDeg      float64                `protobuf:"fixed64,2,opt,name=longitude_deg,json=longitudeDeg,proto3" json:"longitude_deg,omitempty"`                  // Longitude (in degrees)
	AbsoluteAltitudeM float32                `protobuf:"fixed32,3,opt,name=absolute_altitude_m,json=absoluteAltitudeM,proto3" json:"absolute_altitude_m,omitempty"` // Altitude AMSL (in meters)
	YawDeg            float32                `protobuf:"fixed32,4,opt,name=yaw_deg,json=yawDeg,proto3" json:"yaw_deg,omitempty"`                                    // Yaw angle (in degrees, frame is NED, 0 is North, positive is clockwise)
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GotoLocationRequest) Reset() {
	*x = GotoLocationRequest{}
	mi := &file_action_action_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GotoLocationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GotoLocationRequest) ProtoMessage() {}

func (x *GotoLocationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_action_action_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GotoLocationRequest.ProtoReflect.Descriptor instead.
func (*GotoLocationRequest) Descriptor() ([]byte, []int) {
	return file_action_action_proto_rawDescGZIP(), []int{20}
}

func (x *GotoLocationRequest) GetLatitudeDeg() float64 {
	if x != nil {
		return x.LatitudeDeg
	}
	return 0
}

func (x *GotoLocationRequest) GetLongitudeDeg() float64 {
	if x != nil {
		return x.LongitudeDeg
	}
	return 0
}

func (x *GotoLocationRequest) GetAbsoluteAltitudeM() float32 {
	if x != nil {
		return x.AbsoluteAltitudeM
	}
	return 0
}

func (x *GotoLocationRequest) GetYawDeg() float32 {
	if x != nil {
		return x.YawDeg
	}
	return 0
}

type GotoLocationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActionResult  *ActionResult          `protobuf:"bytes,1,opt,name=action_result,json=actionResult,proto3" json:"action_result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GotoLocationResponse) Reset() {
	*x = GotoLocationResponse{}
	mi := &file_action_action_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GotoLocationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GotoLocationResponse) ProtoMessage() {}

func (x *GotoLocationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_action_action_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GotoLocationResponse.ProtoReflect.Descriptor instead.
func (*GotoLocationResponse) Descriptor() ([]byte, []int) {
	return file_action_action_proto_rawDescGZIP(), []int{21}
}

func (x *GotoLocationResponse) GetActionResult() *ActionResult {
	if x != nil {
		return x.ActionResult
	}
	return nil
}

type DoOrbitRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	RadiusM           float32                `protobuf:"fixed32,1,opt,name=radius_m,json=radiusM,proto3" json:"radius_m,omitempty"`                                                    // Radius of circle (in meters)
	VelocityMs        float32                `protobuf:"fixed32,2,opt,name=velocity_ms,json=velocityMs,proto3" json:"velocity_ms,omitempty"`                                           // Tangential velocity (in m/s)
	YawBehavior       OrbitYawBehavior       `protobuf:"varint,3,opt,name=yaw_behavior,json=yawBehavior,proto3,enum=mavsdk.rpc.action.OrbitYawBehavior" json:"yaw_behavior,omitempty"` // Yaw behavior of vehicle (ORBIT_YAW_BEHAVIOUR)
	LatitudeDeg       float64                `protobuf:"fixed64,5,opt,name=latitude_deg,json=latitudeDeg,proto3" json:"latitude_deg,omitempty"`                                        // Center point latitude in degrees. NAN: use current latitude for center
	LongitudeDeg      float64                `protobuf:"fixed64,6,opt,name=longitude_deg,json=longitudeDeg,proto3" json:"longitude_deg,omitempty"`                                     // Center point longitude in degrees. NAN: use current longitude for center
	AbsoluteAltitudeM float64                `protobuf:"fixed64,7,opt,name=absolute_altitude_m,json=absoluteAltitudeM,proto3" json:"absolute_altitude_m,omitempty"`                    // Center point altitude in meters. NAN: use current altitude for center
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *DoOrbitRequest) Reset() {
	*x = DoOrbitRequest{}
	mi := &file_action_action_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DoOrbitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DoOrbitRequest) ProtoMessage() {}

func (x *DoOrbitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_action_action_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DoOrbitRequest.ProtoReflect.Descriptor instead.
func (*DoOrbitRequest) Descriptor() ([]byte, []int) {
	return file_action_action_proto_rawDescGZIP(), []int{22}
}

func (x *DoOrbitRequest) GetRadiusM() float32 {
	if x != nil {
		return x.RadiusM
	}
	return 0
}

func (x *DoOrbitRequest) GetVelocityMs() float32 {
	if x != nil {
		return x.VelocityMs
	}
	return 0
}

func (x *DoOrbitRequest) GetYawBehavior() OrbitYawBehavior {
	if x != nil {
		return x.YawBehavior
	}
	return OrbitYawBehavior_ORBIT_YAW_BEHAVIOR_HOLD_FRONT_TO_CIRCLE_CENTER
}

func (x *DoOrbitRequest) GetLatitudeDeg() float64 {
	if x != nil {
		return x.LatitudeDeg
	}
	return 0
}

func (x *DoOrbitRequest) GetLongitudeDeg() float64 {
	if x != nil {
		return x.LongitudeDeg
	}
	return 0
}

func (x *DoOrbitRequest) GetAbsoluteAltitudeM() float64 {
	if x != nil {
		return x.AbsoluteAltitudeM
	}
	return 0
}

type DoOrbitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActionResult  *ActionResult          `protobuf:"bytes,1,opt,name=action_result,json=actionResult,proto3" json:"action_result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DoOrbitResponse) Reset() {
	*x = DoOrbitResponse{}
	mi := &file_action_action_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DoOrbitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DoOrbitResponse) ProtoMessage() {}

func (x *DoOrbitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_action_action_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DoOrbitResponse.ProtoReflect.Descriptor instead.
func (*DoOrbitResponse) Descriptor() ([]byte, []int) {
	return file_action_action_proto_rawDescGZIP(), []int{23}
}

func (x *DoOrbitResponse) GetActionResult() *ActionResult {
	if x != nil {
		return x.ActionResult
	}
	return nil
}

type HoldRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HoldRequest) Reset() {
	*x = HoldRequest{}
	mi := &file_action_action_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HoldRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HoldRequest) ProtoMessage() {}

func (x *HoldRequest) ProtoReflect() protoreflect.Message {
	mi := &file_action_action_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HoldRequest.ProtoReflect.Descriptor instead.
func (*HoldRequest) Descriptor() ([]byte, []int) {
	return file_action_action_proto_rawDescGZIP(), []int{24}
}

type HoldResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActionResult  *ActionResult          `protobuf:"bytes,1,opt,name=action_result,json=actionResult,proto3" json:"action_result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HoldResponse) Reset() {
	*x = HoldResponse{}
	mi := &file_action_action_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HoldResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HoldResponse) ProtoMessage() {}

func (x *HoldResponse) ProtoReflect() protoreflect.Message {
	mi := &file_action_action_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HoldResponse.ProtoReflect.Descriptor instead.
func (*HoldResponse) Descriptor() ([]byte, []int) {
	return file_action_action_proto_rawDescGZIP(), []int{25}
}

func (x *HoldResponse) GetActionResult() *ActionResult {
	if x != nil {
		return x.ActionResult
	}
	return nil
}

type SetActuatorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         int32                  `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`  // Index of actuator (starting with 1)
	Value         float32                `protobuf:"fixed32,2,opt,name=value,proto3" json:"value,omitempty"` // Value to set the actuator to (normalized from [-1..1])
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetActuatorRequest) Reset() {
	*x = SetActuatorRequest{}
	mi := &file_action_action_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetActuatorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetActuatorRequest) ProtoMessage() {}

func (x *SetActuatorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_action_action_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetActuatorRequest.ProtoReflect.Descriptor instead.
func (*SetActuatorRequest) Descriptor() ([]byte, []int) {
	return file_action_action_proto_rawDescGZIP(), []int{26}
}

func (x *SetActuatorRequest) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *SetActuatorRequest) GetValue() float32 {
	if x != nil {
		return x.Value
	}
	return 0
}

type SetActuatorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActionResult  *ActionResult          `protobuf:"bytes,1,opt,name=action_result,json=actionResult,proto3" json:"action_result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetActuatorResponse) Reset() {
	*x = SetActuatorResponse{}
	mi := &file_action_action_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetActuatorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetActuatorResponse) ProtoMessage() {}

func (x *SetActuatorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_action_action_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetActuatorResponse.ProtoReflect.Descriptor instead.
func (*SetActuatorResponse) Descriptor() ([]byte, []int) {
	return file_action_action_proto_rawDescGZIP(), []int{27}
}

func (x *SetActuatorResponse) GetActionResult() *ActionResult {
	if x != nil {
		return x.ActionResult
	}
	return nil
}

type SetRelayRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         int32                  `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`                                         // Index of relay (starting with 0)
	Setting       RelayCommand           `protobuf:"varint,2,opt,name=setting,proto3,enum=mavsdk.rpc.action.RelayCommand" json:"setting,omitempty"` // Value to set the relay to
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetRelayRequest) Reset() {
	*x = SetRelayRequest{}
	mi := &file_action_action_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetRelayRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetRelayRequest) ProtoMessage() {}

func (x *SetRelayRequest) ProtoReflect() protoreflect.Message {
	mi := &file_action_action_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetRelayRequest.ProtoReflect.Descriptor instead.
func (*SetRelayRequest) Descriptor() ([]byte, []int) {
	return file_action_action_proto_rawDescGZIP(), []int{28}
}

func (x *SetRelayRequest) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *SetRelayRequest) GetSetting() RelayCommand {
	if x != nil {
		return x.Setting
	}
	return RelayCommand_RELAY_COMMAND_ON
}

type SetRelayResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActionResult  *ActionResult          `protobuf:"bytes,1,opt,name=action_result,json=actionResult,proto3" json:"action_result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetRelayResponse) Reset() {
	*x = SetRelayResponse{}
	mi := &file_action_action_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetRelayResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetRelayResponse) ProtoMessage() {}

func (x *SetRelayResponse) ProtoReflect() protoreflect.Message {
	mi := &file_action_action_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetRelayResponse.ProtoReflect.Descriptor instead.
func (*SetRelayResponse) Descriptor() ([]byte, []int) {
	return file_action_action_proto_rawDescGZIP(), []int{29}
}

func (x *SetRelayResponse) GetActionResult() *ActionResult {
	if x != nil {
		return x.ActionResult
	}
	return nil
}

type TransitionToFixedwingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransitionToFixedwingRequest) Reset() {
	*x = TransitionToFixedwingRequest{}
	mi := &file_action_action_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransitionToFixedwingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransitionToFixedwingRequest) ProtoMessage() {}

func (x *TransitionToFixedwingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_action_action_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransitionToFixedwingRequest.ProtoReflect.Descriptor instead.
func (*TransitionToFixedwingRequest) Descriptor() ([]byte, []int) {
	return file_action_action_proto_rawDescGZIP(), []int{30}
}

type TransitionToFixedwingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActionResult  *ActionResult          `protobuf:"bytes,1,opt,name=action_result,json=actionResult,proto3" json:"action_result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransitionToFixedwingResponse) Reset() {
	*x = TransitionToFixedwingResponse{}
	mi := &file_action_action_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransitionToFixedwingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransitionToFixedwingResponse) ProtoMessage() {}

func (x *TransitionToFixedwingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_action_action_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransitionToFixedwingResponse.ProtoReflect.Descriptor instead.
func (*TransitionToFixedwingResponse) Descriptor() ([]byte, []int) {
	return file_action_action_proto_rawDescGZIP(), []int{31}
}

func (x *TransitionToFixedwingResponse) GetActionResult() *ActionResult {
	if x != nil {
		return x.ActionResult
	}
	return nil
}

type TransitionToMulticopterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransitionToMulticopterRequest) Reset() {
	*x = TransitionToMulticopterRequest{}
	mi := &file_action_action_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransitionToMulticopterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransitionToMulticopterRequest) ProtoMessage() {}

func (x *TransitionToMulticopterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_action_action_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransitionToMulticopterRequest.ProtoReflect.Descriptor instead.
func (*TransitionToMulticopterRequest) Descriptor() ([]byte, []int) {
	return file_action_action_proto_rawDescGZIP(), []int{32}
}

type TransitionToMulticopterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActionResult  *ActionResult          `protobuf:"bytes,1,opt,name=action_result,json=actionResult,proto3" json:"action_result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransitionToMulticopterResponse) Reset() {
	*x = TransitionToMulticopterResponse{}
	mi := &file_action_action_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransitionToMulticopterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransitionToMulticopterResponse) ProtoMessage() {}

func (x *TransitionToMulticopterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_action_action_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransitionToMulticopterResponse.ProtoReflect.Descriptor instead.
func (*TransitionToMulticopterResponse) Descriptor() ([]byte, []int) {
	return file_action_action_proto_rawDescGZIP(), []int{33}
}

func (x *TransitionToMulticopterResponse) GetActionResult() *ActionResult {
	if x != nil {
		return x.ActionResult
	}
	return nil
}

type GetTakeoffAltitudeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTakeoffAltitudeRequest) Reset() {
	*x = GetTakeoffAltitudeRequest{}
	mi := &file_action_action_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTakeoffAltitudeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTakeoffAltitudeRequest) ProtoMessage() {}

func (x *GetTakeoffAltitudeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_action_action_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTakeoffAltitudeRequest.ProtoReflect.Descriptor instead.
func (*GetTakeoffAltitudeRequest) Descriptor() ([]byte, []int) {
	return file_action_action_proto_rawDescGZIP(), []int{34}
}

type GetTakeoffAltitudeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActionResult  *ActionResult          `protobuf:"bytes,1,opt,name=action_result,json=actionResult,proto3" json:"action_result,omitempty"`
	Altitude      float32                `protobuf:"fixed32,2,opt,name=altitude,proto3" json:"altitude,omitempty"` // Takeoff altitude relative to ground/takeoff location (in meters)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTakeoffAltitudeResponse) Reset() {
	*x = GetTakeoffAltitudeResponse{}
	mi := &file_action_action_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTakeoffAltitudeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTakeoffAltitudeResponse) ProtoMessage() {}

func (x *GetTakeoffAltitudeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_action_action_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTakeoffAltitudeResponse.ProtoReflect.Descriptor instead.
func (*GetTakeoffAltitudeResponse) Descriptor() ([]byte, []int) {
	return file_action_action_proto_rawDescGZIP(), []int{35}
}

func (x *GetTakeoffAltitudeResponse) GetActionResult() *ActionResult {
	if x != nil {
		return x.ActionResult
	}
	return nil
}

func (x *GetTakeoffAltitudeResponse) GetAltitude() float32 {
	if x != nil {
		return x.Altitude
	}
	return 0
}

type SetTakeoffAltitudeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Altitude      float32                `protobuf:"fixed32,1,opt,name=altitude,proto3" json:"altitude,omitempty"` // Takeoff altitude relative to ground/takeoff location (in meters)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetTakeoffAltitudeRequest) Reset() {
	*x = SetTakeoffAltitudeRequest{}
	mi := &file_action_action_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetTakeoffAltitudeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetTakeoffAltitudeRequest) ProtoMessage() {}

func (x *SetTakeoffAltitudeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_action_action_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetTakeoffAltitudeRequest.ProtoReflect.Descriptor instead.
func (*SetTakeoffAltitudeRequest) Descriptor() ([]byte, []int) {
	return file_action_action_proto_rawDescGZIP(), []int{36}
}

func (x *SetTakeoffAltitudeRequest) GetAltitude() float32 {
	if x != nil {
		return x.Altitude
	}
	return 0
}

type SetTakeoffAltitudeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActionResult  *ActionResult          `protobuf:"bytes,1,opt,name=action_result,json=actionResult,proto3" json:"action_result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetTakeoffAltitudeResponse) Reset() {
	*x = SetTakeoffAltitudeResponse{}
	mi := &file_action_action_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetTakeoffAltitudeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetTakeoffAltitudeResponse) ProtoMessage() {}

func (x *SetTakeoffAltitudeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_action_action_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetTakeoffAltitudeResponse.ProtoReflect.Descriptor instead.
func (*SetTakeoffAltitudeResponse) Descriptor() ([]byte, []int) {
	return file_action_action_proto_rawDescGZIP(), []int{37}
}

func (x *SetTakeoffAltitudeResponse) GetActionResult() *ActionResult {
	if x != nil {
		return x.ActionResult
	}
	return nil
}

type GetReturnToLaunchAltitudeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReturnToLaunchAltitudeRequest) Reset() {
	*x = GetReturnToLaunchAltitudeRequest{}
	mi := &file_action_action_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReturnToLaunchAltitudeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReturnToLaunchAltitudeRequest) ProtoMessage() {}

func (x *GetReturnToLaunchAltitudeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_action_action_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReturnToLaunchAltitudeRequest.ProtoReflect.Descriptor instead.
func (*GetReturnToLaunchAltitudeRequest) Descriptor() ([]byte, []int) {
	return file_action_action_proto_rawDescGZIP(), []int{38}
}

type GetReturnToLaunchAltitudeResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ActionResult      *ActionResult          `protobuf:"bytes,1,opt,name=action_result,json=actionResult,proto3" json:"action_result,omitempty"`
	RelativeAltitudeM float32                `protobuf:"fixed32,2,opt,name=relative_altitude_m,json=relativeAltitudeM,proto3" json:"relative_altitude_m,omitempty"` // Return altitude relative to takeoff location (in meters)
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetReturnToLaunchAltitudeResponse) Reset() {
	*x = GetReturnToLaunchAltitudeResponse{}
	mi := &file_action_action_proto_msgTypes[39]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReturnToLaunchAltitudeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReturnToLaunchAltitudeResponse) ProtoMessage() {}

func (x *GetReturnToLaunchAltitudeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_action_action_proto_msgTypes[39]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReturnToLaunchAltitudeResponse.ProtoReflect.Descriptor instead.
func (*GetReturnToLaunchAltitudeResponse) Descriptor() ([]byte, []int) {
	return file_action_action_proto_rawDescGZIP(), []int{39}
}

func (x *GetReturnToLaunchAltitudeResponse) GetActionResult() *ActionResult {
	if x != nil {
		return x.ActionResult
	}
	return nil
}

func (x *GetReturnToLaunchAltitudeResponse) GetRelativeAltitudeM() float32 {
	if x != nil {
		return x.RelativeAltitudeM
	}
	return 0
}

type SetReturnToLaunchAltitudeRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	RelativeAltitudeM float32                `protobuf:"fixed32,1,opt,name=relative_altitude_m,json=relativeAltitudeM,proto3" json:"relative_altitude_m,omitempty"` // Return altitude relative to takeoff location (in meters)
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SetReturnToLaunchAltitudeRequest) Reset() {
	*x = SetReturnToLaunchAltitudeRequest{}
	mi := &file_action_action_proto_msgTypes[40]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetReturnToLaunchAltitudeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetReturnToLaunchAltitudeRequest) ProtoMessage() {}

func (x *SetReturnToLaunchAltitudeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_action_action_proto_msgTypes[40]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetReturnToLaunchAltitudeRequest.ProtoReflect.Descriptor instead.
func (*SetReturnToLaunchAltitudeRequest) Descriptor() ([]byte, []int) {
	return file_action_action_proto_rawDescGZIP(), []int{40}
}

func (x *SetReturnToLaunchAltitudeRequest) GetRelativeAltitudeM() float32 {
	if x != nil {
		return x.RelativeAltitudeM
	}
	return 0
}

type SetReturnToLaunchAltitudeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActionResult  *ActionResult          `protobuf:"bytes,1,opt,name=action_result,json=actionResult,proto3" json:"action_result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetReturnToLaunchAltitudeResponse) Reset() {
	*x = SetReturnToLaunchAltitudeResponse{}
	mi := &file_action_action_proto_msgTypes[41]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetReturnToLaunchAltitudeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetReturnToLaunchAltitudeResponse) ProtoMessage() {}

func (x *SetReturnToLaunchAltitudeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_action_action_proto_msgTypes[41]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetReturnToLaunchAltitudeResponse.ProtoReflect.Descriptor instead.
func (*SetReturnToLaunchAltitudeResponse) Descriptor() ([]byte, []int) {
	return file_action_action_proto_rawDescGZIP(), []int{41}
}

func (x *SetReturnToLaunchAltitudeResponse) GetActionResult() *ActionResult {
	if x != nil {
		return x.ActionResult
	}
	return nil
}

type SetCurrentSpeedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SpeedMS       float32                `protobuf:"fixed32,1,opt,name=speed_m_s,json=speedMS,proto3" json:"speed_m_s,omitempty"` // Speed in meters/second
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetCurrentSpeedRequest) Reset() {
	*x = SetCurrentSpeedRequest{}
	mi := &file_action_action_proto_msgTypes[42]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetCurrentSpeedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetCurrentSpeedRequest) ProtoMessage() {}

func (x *SetCurrentSpeedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_action_action_proto_msgTypes[42]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetCurrentSpeedRequest.ProtoReflect.Descriptor instead.
func (*SetCurrentSpeedRequest) Descriptor() ([]byte, []int) {
	return file_action_action_proto_rawDescGZIP(), []int{42}
}

func (x *SetCurrentSpeedRequest) GetSpeedMS() float32 {
	if x != nil {
		return x.SpeedMS
	}
	return 0
}

type SetCurrentSpeedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActionResult  *ActionResult          `protobuf:"bytes,1,opt,name=action_result,json=actionResult,proto3" json:"action_result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetCurrentSpeedResponse) Reset() {
	*x = SetCurrentSpeedResponse{}
	mi := &file_action_action_proto_msgTypes[43]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetCurrentSpeedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetCurrentSpeedResponse) ProtoMessage() {}

func (x *SetCurrentSpeedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_action_action_proto_msgTypes[43]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetCurrentSpeedResponse.ProtoReflect.Descriptor instead.
func (*SetCurrentSpeedResponse) Descriptor() ([]byte, []int) {
	return file_action_action_proto_rawDescGZIP(), []int{43}
}

func (x *SetCurrentSpeedResponse) GetActionResult() *ActionResult {
	if x != nil {
		return x.ActionResult
	}
	return nil
}

type SetGpsGlobalOriginRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	LatitudeDeg       float64                `protobuf:"fixed64,1,opt,name=latitude_deg,json=latitudeDeg,proto3" json:"latitude_deg,omitempty"`                     // Latitude (in degrees)
	LongitudeDeg      float64                `protobuf:"fixed64,2,opt,name=longitude_deg,json=longitudeDeg,proto3" json:"longitude_deg,omitempty"`                  // Longitude (in degrees)
	AbsoluteAltitudeM float32                `protobuf:"fixed32,3,opt,name=absolute_altitude_m,json=absoluteAltitudeM,proto3" json:"absolute_altitude_m,omitempty"` // Altitude AMSL (in meters)
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SetGpsGlobalOriginRequest) Reset() {
	*x = SetGpsGlobalOriginRequest{}
	mi := &file_action_action_proto_msgTypes[44]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetGpsGlobalOriginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetGpsGlobalOriginRequest) ProtoMessage() {}

func (x *SetGpsGlobalOriginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_action_action_proto_msgTypes[44]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetGpsGlobalOriginRequest.ProtoReflect.Descriptor instead.
func (*SetGpsGlobalOriginRequest) Descriptor() ([]byte, []int) {
	return file_action_action_proto_rawDescGZIP(), []int{44}
}

func (x *SetGpsGlobalOriginRequest) GetLatitudeDeg() float64 {
	if x != nil {
		return x.LatitudeDeg
	}
	return 0
}

func (x *SetGpsGlobalOriginRequest) GetLongitudeDeg() float64 {
	if x != nil {
		return x.LongitudeDeg
	}
	return 0
}

func (x *SetGpsGlobalOriginRequest) GetAbsoluteAltitudeM() float32 {
	if x != nil {
		return x.AbsoluteAltitudeM
	}
	return 0
}

type SetGpsGlobalOriginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActionResult  *ActionResult          `protobuf:"bytes,1,opt,name=action_result,json=actionResult,proto3" json:"action_result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetGpsGlobalOriginResponse) Reset() {
	*x = SetGpsGlobalOriginResponse{}
	mi := &file_action_action_proto_msgTypes[45]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetGpsGlobalOriginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetGpsGlobalOriginResponse) ProtoMessage() {}

func (x *SetGpsGlobalOriginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_action_action_proto_msgTypes[45]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetGpsGlobalOriginResponse.ProtoReflect.Descriptor instead.
func (*SetGpsGlobalOriginResponse) Descriptor() ([]byte, []int) {
	return file_action_action_proto_rawDescGZIP(), []int{45}
}

func (x *SetGpsGlobalOriginResponse) GetActionResult() *ActionResult {
	if x != nil {
		return x.ActionResult
	}
	return nil
}

type SetHomeRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	UseCurrentLocation bool                   `protobuf:"varint,1,opt,name=use_current_location,json=useCurrentLocation,proto3" json:"use_current_location,omitempty"` // Use current location
	LatitudeDeg        float64                `protobuf:"fixed64,2,opt,name=latitude_deg,json=latitudeDeg,proto3" json:"latitude_deg,omitempty"`                       // Latitude (in degrees)
	LongitudeDeg       float64                `protobuf:"fixed64,3,opt,name=longitude_deg,json=longitudeDeg,proto3" json:"longitude_deg,omitempty"`                    // Longitude (in degrees)
	AbsoluteAltitudeM  float32                `protobuf:"fixed32,4,opt,name=absolute_altitude_m,json=absoluteAltitudeM,proto3" json:"absolute_altitude_m,omitempty"`   // Altitude AMSL (in meters)
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *SetHomeRequest) Reset() {
	*x = SetHomeRequest{}
	mi := &file_action_action_proto_msgTypes[46]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetHomeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetHomeRequest) ProtoMessage() {}

func (x *SetHomeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_action_action_proto_msgTypes[46]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetHomeRequest.ProtoReflect.Descriptor instead.
func (*SetHomeRequest) Descriptor() ([]byte, []int) {
	return file_action_action_proto_rawDescGZIP(), []int{46}
}

func (x *SetHomeRequest) GetUseCurrentLocation() bool {
	if x != nil {
		return x.UseCurrentLocation
	}
	return false
}

func (x *SetHomeRequest) GetLatitudeDeg() float64 {
	if x != nil {
		return x.LatitudeDeg
	}
	return 0
}

func (x *SetHomeRequest) GetLongitudeDeg() float64 {
	if x != nil {
		return x.LongitudeDeg
	}
	return 0
}

func (x *SetHomeRequest) GetAbsoluteAltitudeM() float32 {
	if x != nil {
		return x.AbsoluteAltitudeM
	}
	return 0
}

type SetHomeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActionResult  *ActionResult          `protobuf:"bytes,1,opt,name=action_result,json=actionResult,proto3" json:"action_result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetHomeResponse) Reset() {
	*x = SetHomeResponse{}
	mi := &file_action_action_proto_msgTypes[47]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetHomeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetHomeResponse) ProtoMessage() {}

func (x *SetHomeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_action_action_proto_msgTypes[47]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetHomeResponse.ProtoReflect.Descriptor instead.
func (*SetHomeResponse) Descriptor() ([]byte, []int) {
	return file_action_action_proto_rawDescGZIP(), []int{47}
}

func (x *SetHomeResponse) GetActionResult() *ActionResult {
	if x != nil {
		return x.ActionResult
	}
	return nil
}

// Result type.
type ActionResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        ActionResult_Result    `protobuf:"varint,1,opt,name=result,proto3,enum=mavsdk.rpc.action.ActionResult_Result" json:"result,omitempty"` // Result enum value
	ResultStr     string                 `protobuf:"bytes,2,opt,name=result_str,json=resultStr,proto3" json:"result_str,omitempty"`                      // Human-readable English string describing the result
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActionResult) Reset() {
	*x = ActionResult{}
	mi := &file_action_action_proto_msgTypes[48]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionResult) ProtoMessage() {}

func (x *ActionResult) ProtoReflect() protoreflect.Message {
	mi := &file_action_action_proto_msgTypes[48]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionResult.ProtoReflect.Descriptor instead.
func (*ActionResult) Descriptor() ([]byte, []int) {
	return file_action_action_proto_rawDescGZIP(), []int{48}
}

func (x *ActionResult) GetResult() ActionResult_Result {
	if x != nil {
		return x.Result
	}
	return ActionResult_RESULT_UNKNOWN
}

func (x *ActionResult) GetResultStr() string {
	if x != nil {
		return x.ResultStr
	}
	return ""
}

var File_action_action_proto protoreflect.FileDescriptor

const file_action_action_proto_rawDesc = "" +
	"\n" +
	"\x13action/action.proto\x12\x11mavsdk.rpc.action\x1a\x14mavsdk_options.proto\"\f\n" +
	"\n" +
	"ArmRequest\"S\n" +
	"\vArmResponse\x12D\n" +
	"\raction_result\x18\x01 \x01(\v2\x1f.mavsdk.rpc.action.ActionResultR\factionResult\"\x11\n" +
	"\x0fArmForceRequest\"X\n" +
	"\x10ArmForceResponse\x12D\n" +
	"\raction_result\x18\x01 \x01(\v2\x1f.mavsdk.rpc.action.ActionResultR\factionResult\"\x0f\n" +
	"\rDisarmRequest\"V\n" +
	"\x0eDisarmResponse\x12D\n" +
	"\raction_result\x18\x01 \x01(\v2\x1f.mavsdk.rpc.action.ActionResultR\factionResult\"\x10\n" +
	"\x0eTakeoffRequest\"W\n" +
	"\x0fTakeoffResponse\x12D\n" +
	"\raction_result\x18\x01 \x01(\v2\x1f.mavsdk.rpc.action.ActionResultR\factionResult\"\r\n" +
	"\vLandRequest\"T\n" +
	"\fLandResponse\x12D\n" +
	"\raction_result\x18\x01 \x01(\v2\x1f.mavsdk.rpc.action.ActionResultR\factionResult\"\x0f\n" +
	"\rRebootRequest\"V\n" +
	"\x0eRebootResponse\x12D\n" +
	"\raction_result\x18\x01 \x01(\v2\x1f.mavsdk.rpc.action.ActionResultR\factionResult\"\x11\n" +
	"\x0fShutdownRequest\"X\n" +
	"\x10ShutdownResponse\x12D\n" +
	"\raction_result\x18\x01 \x01(\v2\x1f.mavsdk.rpc.action.ActionResultR\factionResult\"\x12\n" +
	"\x10TerminateRequest\"Y\n" +
	"\x11TerminateResponse\x12D\n" +
	"\raction_result\x18\x01 \x01(\v2\x1f.mavsdk.rpc.action.ActionResultR\factionResult\"\r\n" +
	"\vKillRequest\"T\n" +
	"\fKillResponse\x12D\n" +
	"\raction_result\x18\x01 \x01(\v2\x1f.mavsdk.rpc.action.ActionResultR\factionResult\"\x17\n" +
	"\x15ReturnToLaunchRequest\"^\n" +
	"\x16ReturnToLaunchResponse\x12D\n" +
	"\raction_result\x18\x01 \x01(\v2\x1f.mavsdk.rpc.action.ActionResultR\factionResult\"\xa6\x01\n" +
	"\x13GotoLocationRequest\x12!\n" +
	"\flatitude_deg\x18\x01 \x01(\x01R\vlatitudeDeg\x12#\n" +
	"\rlongitude_deg\x18\x02 \x01(\x01R\flongitudeDeg\x12.\n" +
	"\x13absolute_altitude_m\x18\x03 \x01(\x02R\x11absoluteAltitudeM\x12\x17\n" +
	"\ayaw_deg\x18\x04 \x01(\x02R\x06yawDeg\"\\\n" +
	"\x14GotoLocationResponse\x12D\n" +
	"\raction_result\x18\x01 \x01(\v2\x1f.mavsdk.rpc.action.ActionResultR\factionResult\"\xa7\x02\n" +
	"\x0eDoOrbitRequest\x12\x19\n" +
	"\bradius_m\x18\x01 \x01(\x02R\aradiusM\x12\x1f\n" +
	"\vvelocity_ms\x18\x02 \x01(\x02R\n" +
	"velocityMs\x12F\n" +
	"\fyaw_behavior\x18\x03 \x01(\x0e2#.mavsdk.rpc.action.OrbitYawBehaviorR\vyawBehavior\x12*\n" +
	"\flatitude_deg\x18\x05 \x01(\x01B\a\x82\xb5\x18\x03NaNR\vlatitudeDeg\x12,\n" +
	"\rlongitude_deg\x18\x06 \x01(\x01B\a\x82\xb5\x18\x03NaNR\flongitudeDeg\x127\n" +
	"\x13absolute_altitude_m\x18\a \x01(\x01B\a\x82\xb5\x18\x03NaNR\x11absoluteAltitudeM\"W\n" +
	"\x0fDoOrbitResponse\x12D\n" +
	"\raction_result\x18\x01 \x01(\v2\x1f.mavsdk.rpc.action.ActionResultR\factionResult\"\r\n" +
	"\vHoldRequest\"T\n" +
	"\fHoldResponse\x12D\n" +
	"\raction_result\x18\x01 \x01(\v2\x1f.mavsdk.rpc.action.ActionResultR\factionResult\"@\n" +
	"\x12SetActuatorRequest\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x05R\x05index\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x02R\x05value\"[\n" +
	"\x13SetActuatorResponse\x12D\n" +
	"\raction_result\x18\x01 \x01(\v2\x1f.mavsdk.rpc.action.ActionResultR\factionResult\"b\n" +
	"\x0fSetRelayRequest\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x05R\x05index\x129\n" +
	"\asetting\x18\x02 \x01(\x0e2\x1f.mavsdk.rpc.action.RelayCommandR\asetting\"X\n" +
	"\x10SetRelayResponse\x12D\n" +
	"\raction_result\x18\x01 \x01(\v2\x1f.mavsdk.rpc.action.ActionResultR\factionResult\"\x1e\n" +
	"\x1cTransitionToFixedwingRequest\"e\n" +
	"\x1dTransitionToFixedwingResponse\x12D\n" +
	"\raction_result\x18\x01 \x01(\v2\x1f.mavsdk.rpc.action.ActionResultR\factionResult\" \n" +
	"\x1eTransitionToMulticopterRequest\"g\n" +
	"\x1fTransitionToMulticopterResponse\x12D\n" +
	"\raction_result\x18\x01 \x01(\v2\x1f.mavsdk.rpc.action.ActionResultR\factionResult\"\x1b\n" +
	"\x19GetTakeoffAltitudeRequest\"~\n" +
	"\x1aGetTakeoffAltitudeResponse\x12D\n" +
	"\raction_result\x18\x01 \x01(\v2\x1f.mavsdk.rpc.action.ActionResultR\factionResult\x12\x1a\n" +
	"\baltitude\x18\x02 \x01(\x02R\baltitude\"7\n" +
	"\x19SetTakeoffAltitudeRequest\x12\x1a\n" +
	"\baltitude\x18\x01 \x01(\x02R\baltitude\"b\n" +
	"\x1aSetTakeoffAltitudeResponse\x12D\n" +
	"\raction_result\x18\x01 \x01(\v2\x1f.mavsdk.rpc.action.ActionResultR\factionResult\"\"\n" +
	" GetReturnToLaunchAltitudeRequest\"\x99\x01\n" +
	"!GetReturnToLaunchAltitudeResponse\x12D\n" +
	"\raction_result\x18\x01 \x01(\v2\x1f.mavsdk.rpc.action.ActionResultR\factionResult\x12.\n" +
	"\x13relative_altitude_m\x18\x02 \x01(\x02R\x11relativeAltitudeM\"R\n" +
	" SetReturnToLaunchAltitudeRequest\x12.\n" +
	"\x13relative_altitude_m\x18\x01 \x01(\x02R\x11relativeAltitudeM\"i\n" +
	"!SetReturnToLaunchAltitudeResponse\x12D\n" +
	"\raction_result\x18\x01 \x01(\v2\x1f.mavsdk.rpc.action.ActionResultR\factionResult\"4\n" +
	"\x16SetCurrentSpeedRequest\x12\x1a\n" +
	"\tspeed_m_s\x18\x01 \x01(\x02R\aspeedMS\"_\n" +
	"\x17SetCurrentSpeedResponse\x12D\n" +
	"\raction_result\x18\x01 \x01(\v2\x1f.mavsdk.rpc.action.ActionResultR\factionResult\"\x93\x01\n" +
	"\x19SetGpsGlobalOriginRequest\x12!\n" +
	"\flatitude_deg\x18\x01 \x01(\x01R\vlatitudeDeg\x12#\n" +
	"\rlongitude_deg\x18\x02 \x01(\x01R\flongitudeDeg\x12.\n" +
	"\x13absolute_altitude_m\x18\x03 \x01(\x02R\x11absoluteAltitudeM\"b\n" +
	"\x1aSetGpsGlobalOriginResponse\x12D\n" +
	"\raction_result\x18\x01 \x01(\v2\x1f.mavsdk.rpc.action.ActionResultR\factionResult\"\xba\x01\n" +
	"\x0eSetHomeRequest\x120\n" +
	"\x14use_current_location\x18\x01 \x01(\bR\x12useCurrentLocation\x12!\n" +
	"\flatitude_deg\x18\x02 \x01(\x01R\vlatitudeDeg\x12#\n" +
	"\rlongitude_deg\x18\x03 \x01(\x01R\flongitudeDeg\x12.\n" +
	"\x13absolute_altitude_m\x18\x04 \x01(\x02R\x11absoluteAltitudeM\"W\n" +
	"\x0fSetHomeResponse\x12D\n" +
	"\raction_result\x18\x01 \x01(\v2\x1f.mavsdk.rpc.action.ActionResultR\factionResult\"\xa0\x04\n" +
	"\fActionResult\x12>\n" +
	"\x06result\x18\x01 \x01(\x0e2&.mavsdk.rpc.action.ActionResult.ResultR\x06result\x12\x1d\n" +
	"\n" +
	"result_str\x18\x02 \x01(\tR\tresultStr\"\xb0\x03\n" +
	"\x06Result\x12\x12\n" +
	"\x0eRESULT_UNKNOWN\x10\x00\x12\x12\n" +
	"\x0eRESULT_SUCCESS\x10\x01\x12\x14\n" +
	"\x10RESULT_NO_SYSTEM\x10\x02\x12\x1b\n" +
	"\x17RESULT_CONNECTION_ERROR\x10\x03\x12\x0f\n" +
	"\vRESULT_BUSY\x10\x04\x12\x19\n" +
	"\x15RESULT_COMMAND_DENIED\x10\x05\x12.\n" +
	"*RESULT_COMMAND_DENIED_LANDED_STATE_UNKNOWN\x10\x06\x12$\n" +
	" RESULT_COMMAND_DENIED_NOT_LANDED\x10\a\x12\x12\n" +
	"\x0eRESULT_TIMEOUT\x10\b\x12*\n" +
	"&RESULT_VTOL_TRANSITION_SUPPORT_UNKNOWN\x10\t\x12%\n" +
	"!RESULT_NO_VTOL_TRANSITION_SUPPORT\x10\n" +
	"\x12\x1a\n" +
	"\x16RESULT_PARAMETER_ERROR\x10\v\x12\x16\n" +
	"\x12RESULT_UNSUPPORTED\x10\f\x12\x11\n" +
	"\rRESULT_FAILED\x10\r\x12\x1b\n" +
	"\x17RESULT_INVALID_ARGUMENT\x10\x0e*\xf3\x01\n" +
	"\x10OrbitYawBehavior\x122\n" +
	".ORBIT_YAW_BEHAVIOR_HOLD_FRONT_TO_CIRCLE_CENTER\x10\x00\x12+\n" +
	"'ORBIT_YAW_BEHAVIOR_HOLD_INITIAL_HEADING\x10\x01\x12#\n" +
	"\x1fORBIT_YAW_BEHAVIOR_UNCONTROLLED\x10\x02\x123\n" +
	"/ORBIT_YAW_BEHAVIOR_HOLD_FRONT_TANGENT_TO_CIRCLE\x10\x03\x12$\n" +
	" ORBIT_YAW_BEHAVIOR_RC_CONTROLLED\x10\x04*;\n" +
	"\fRelayCommand\x12\x14\n" +
	"\x10RELAY_COMMAND_ON\x10\x00\x12\x15\n" +
	"\x11RELAY_COMMAND_OFF\x10\x012\xcd\x12\n" +
	"\rActionService\x12F\n" +
	"\x03Arm\x12\x1d.mavsdk.rpc.action.ArmRequest\x1a\x1e.mavsdk.rpc.action.ArmResponse\"\x00\x12U\n" +
	"\bArmForce\x12\".mavsdk.rpc.action.ArmForceRequest\x1a#.mavsdk.rpc.action.ArmForceResponse\"\x00\x12O\n" +
	"\x06Disarm\x12 .mavsdk.rpc.action.DisarmRequest\x1a!.mavsdk.rpc.action.DisarmResponse\"\x00\x12R\n" +
	"\aTakeoff\x12!.mavsdk.rpc.action.TakeoffRequest\x1a\".mavsdk.rpc.action.TakeoffResponse\"\x00\x12I\n" +
	"\x04Land\x12\x1e.mavsdk.rpc.action.LandRequest\x1a\x1f.mavsdk.rpc.action.LandResponse\"\x00\x12O\n" +
	"\x06Reboot\x12 .mavsdk.rpc.action.RebootRequest\x1a!.mavsdk.rpc.action.RebootResponse\"\x00\x12U\n" +
	"\bShutdown\x12\".mavsdk.rpc.action.ShutdownRequest\x1a#.mavsdk.rpc.action.ShutdownResponse\"\x00\x12X\n" +
	"\tTerminate\x12#.mavsdk.rpc.action.TerminateRequest\x1a$.mavsdk.rpc.action.TerminateResponse\"\x00\x12I\n" +
	"\x04Kill\x12\x1e.mavsdk.rpc.action.KillRequest\x1a\x1f.mavsdk.rpc.action.KillResponse\"\x00\x12g\n" +
	"\x0eReturnToLaunch\x12(.mavsdk.rpc.action.ReturnToLaunchRequest\x1a).mavsdk.rpc.action.ReturnToLaunchResponse\"\x00\x12a\n" +
	"\fGotoLocation\x12&.mavsdk.rpc.action.GotoLocationRequest\x1a'.mavsdk.rpc.action.GotoLocationResponse\"\x00\x12R\n" +
	"\aDoOrbit\x12!.mavsdk.rpc.action.DoOrbitRequest\x1a\".mavsdk.rpc.action.DoOrbitResponse\"\x00\x12I\n" +
	"\x04Hold\x12\x1e.mavsdk.rpc.action.HoldRequest\x1a\x1f.mavsdk.rpc.action.HoldResponse\"\x00\x12^\n" +
	"\vSetActuator\x12%.mavsdk.rpc.action.SetActuatorRequest\x1a&.mavsdk.rpc.action.SetActuatorResponse\"\x00\x12U\n" +
	"\bSetRelay\x12\".mavsdk.rpc.action.SetRelayRequest\x1a#.mavsdk.rpc.action.SetRelayResponse\"\x00\x12|\n" +
	"\x15TransitionToFixedwing\x12/.mavsdk.rpc.action.TransitionToFixedwingRequest\x1a0.mavsdk.rpc.action.TransitionToFixedwingResponse\"\x00\x12\x82\x01\n" +
	"\x17TransitionToMulticopter\x121.mavsdk.rpc.action.TransitionToMulticopterRequest\x1a2.mavsdk.rpc.action.TransitionToMulticopterResponse\"\x00\x12s\n" +
	"\x12GetTakeoffAltitude\x12,.mavsdk.rpc.action.GetTakeoffAltitudeRequest\x1a-.mavsdk.rpc.action.GetTakeoffAltitudeResponse\"\x00\x12s\n" +
	"\x12SetTakeoffAltitude\x12,.mavsdk.rpc.action.SetTakeoffAltitudeRequest\x1a-.mavsdk.rpc.action.SetTakeoffAltitudeResponse\"\x00\x12\x88\x01\n" +
	"\x19GetReturnToLaunchAltitude\x123.mavsdk.rpc.action.GetReturnToLaunchAltitudeRequest\x1a4.mavsdk.rpc.action.GetReturnToLaunchAltitudeResponse\"\x00\x12\x88\x01\n" +
	"\x19SetReturnToLaunchAltitude\x123.mavsdk.rpc.action.SetReturnToLaunchAltitudeRequest\x1a4.mavsdk.rpc.action.SetReturnToLaunchAltitudeResponse\"\x00\x12j\n" +
	"\x0fSetCurrentSpeed\x12).mavsdk.rpc.action.SetCurrentSpeedRequest\x1a*.mavsdk.rpc.action.SetCurrentSpeedResponse\"\x00\x12w\n" +
	"\x12SetGpsGlobalOrigin\x12,.mavsdk.rpc.action.SetGpsGlobalOriginRequest\x1a-.mavsdk.rpc.action.SetGpsGlobalOriginResponse\"\x04\x80\xb5\x18\x01\x12V\n" +
	"\aSetHome\x12!.mavsdk.rpc.action.SetHomeRequest\x1a\".mavsdk.rpc.action.SetHomeResponse\"\x04\x80\xb5\x18\x01B\x1f\n" +
	"\x10io.mavsdk.actionB\vActionProtob\x06proto3"

var (
	file_action_action_proto_rawDescOnce sync.Once
	file_action_action_proto_rawDescData []byte
)

func file_action_action_proto_rawDescGZIP() []byte {
	file_action_action_proto_rawDescOnce.Do(func() {
		file_action_action_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_action_action_proto_rawDesc), len(file_action_action_proto_rawDesc)))
	})
	return file_action_action_proto_rawDescData
}

var file_action_action_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_action_action_proto_msgTypes = make([]protoimpl.MessageInfo, 49)
var file_action_action_proto_goTypes = []any{
	(OrbitYawBehavior)(0),                     // 0: mavsdk.rpc.action.OrbitYawBehavior
	(RelayCommand)(0),                         // 1: mavsdk.rpc.action.RelayCommand
	(ActionResult_Result)(0),                  // 2: mavsdk.rpc.action.ActionResult.Result
	(*ArmRequest)(nil),                        // 3: mavsdk.rpc.action.ArmRequest
	(*ArmResponse)(nil),                       // 4: mavsdk.rpc.action.ArmResponse
	(*ArmForceRequest)(nil),                   // 5: mavsdk.rpc.action.ArmForceRequest
	(*ArmForceResponse)(nil),                  // 6: mavsdk.rpc.action.ArmForceResponse
	(*DisarmRequest)(nil),                     // 7: mavsdk.rpc.action.DisarmRequest
	(*DisarmResponse)(nil),                    // 8: mavsdk.rpc.action.DisarmResponse
	(*TakeoffRequest)(nil),                    // 9: mavsdk.rpc.action.TakeoffRequest
	(*TakeoffResponse)(nil),                   // 10: mavsdk.rpc.action.TakeoffResponse
	(*LandRequest)(nil),                       // 11: mavsdk.rpc.action.LandRequest
	(*LandResponse)(nil),                      // 12: mavsdk.rpc.action.LandResponse
	(*RebootRequest)(nil),                     // 13: mavsdk.rpc.action.RebootRequest
	(*RebootResponse)(nil),                    // 14: mavsdk.rpc.action.RebootResponse
	(*ShutdownRequest)(nil),                   // 15: mavsdk.rpc.action.ShutdownRequest
	(*ShutdownResponse)(nil),                  // 16: mavsdk.rpc.action.ShutdownResponse
	(*TerminateRequest)(nil),                  // 17: mavsdk.rpc.action.TerminateRequest
	(*TerminateResponse)(nil),                 // 18: mavsdk.rpc.action.TerminateResponse
	(*KillRequest)(nil),                       // 19: mavsdk.rpc.action.KillRequest
	(*KillResponse)(nil),                      // 20: mavsdk.rpc.action.KillResponse
	(*ReturnToLaunchRequest)(nil),             // 21: mavsdk.rpc.action.ReturnToLaunchRequest
	(*ReturnToLaunchResponse)(nil),            // 22: mavsdk.rpc.action.ReturnToLaunchResponse
	(*GotoLocationRequest)(nil),               // 23: mavsdk.rpc.action.GotoLocationRequest
	(*GotoLocationResponse)(nil),              // 24: mavsdk.rpc.action.GotoLocationResponse
	(*DoOrbitRequest)(nil),                    // 25: mavsdk.rpc.action.DoOrbitRequest
	(*DoOrbitResponse)(nil),                   // 26: mavsdk.rpc.action.DoOrbitResponse
	(*HoldRequest)(nil),                       // 27: mavsdk.rpc.action.HoldRequest
	(*HoldResponse)(nil),                      // 28: mavsdk.rpc.action.HoldResponse
	(*SetActuatorRequest)(nil),                // 29: mavsdk.rpc.action.SetActuatorRequest
	(*SetActuatorResponse)(nil),               // 30: mavsdk.rpc.action.SetActuatorResponse
	(*SetRelayRequest)(nil),                   // 31: mavsdk.rpc.action.SetRelayRequest
	(*SetRelayResponse)(nil),                  // 32: mavsdk.rpc.action.SetRelayResponse
	(*TransitionToFixedwingRequest)(nil),      // 33: mavsdk.rpc.action.TransitionToFixedwingRequest
	(*TransitionToFixedwingResponse)(nil),     // 34: mavsdk.rpc.action.TransitionToFixedwingResponse
	(*TransitionToMulticopterRequest)(nil),    // 35: mavsdk.rpc.action.TransitionToMulticopterRequest
	(*TransitionToMulticopterResponse)(nil),   // 36: mavsdk.rpc.action.TransitionToMulticopterResponse
	(*GetTakeoffAltitudeRequest)(nil),         // 37: mavsdk.rpc.action.GetTakeoffAltitudeRequest
	(*GetTakeoffAltitudeResponse)(nil),        // 38: mavsdk.rpc.action.GetTakeoffAltitudeResponse
	(*SetTakeoffAltitudeRequest)(nil),         // 39: mavsdk.rpc.action.SetTakeoffAltitudeRequest
	(*SetTakeoffAltitudeResponse)(nil),        // 40: mavsdk.rpc.action.SetTakeoffAltitudeResponse
	(*GetReturnToLaunchAltitudeRequest)(nil),  // 41: mavsdk.rpc.action.GetReturnToLaunchAltitudeRequest
	(*GetReturnToLaunchAltitudeResponse)(nil), // 42: mavsdk.rpc.action.GetReturnToLaunchAltitudeResponse
	(*SetReturnToLaunchAltitudeRequest)(nil),  // 43: mavsdk.rpc.action.SetReturnToLaunchAltitudeRequest
	(*SetReturnToLaunchAltitudeResponse)(nil), // 44: mavsdk.rpc.action.SetReturnToLaunchAltitudeResponse
	(*SetCurrentSpeedRequest)(nil),            // 45: mavsdk.rpc.action.SetCurrentSpeedRequest
	(*SetCurrentSpeedResponse)(nil),           // 46: mavsdk.rpc.action.SetCurrentSpeedResponse
	(*SetGpsGlobalOriginRequest)(nil),         // 47: mavsdk.rpc.action.SetGpsGlobalOriginRequest
	(*SetGpsGlobalOriginResponse)(nil),        // 48: mavsdk.rpc.action.SetGpsGlobalOriginResponse
	(*SetHomeRequest)(nil),                    // 49: mavsdk.rpc.action.SetHomeRequest
	(*SetHomeResponse)(nil),                   // 50: mavsdk.rpc.action.SetHomeResponse
	(*ActionResult)(nil),                      // 51: mavsdk.rpc.action.ActionResult
}
var file_action_action_proto_depIdxs = []int32{
	51, // 0: mavsdk.rpc.action.ArmResponse.action_result:type_name -> mavsdk.rpc.action.ActionResult
	51, // 1: mavsdk.rpc.action.ArmForceResponse.action_result:type_name -> mavsdk.rpc.action.ActionResult
	51, // 2: mavsdk.rpc.action.DisarmResponse.action_result:type_name -> mavsdk.rpc.action.ActionResult
	51, // 3: mavsdk.rpc.action.TakeoffResponse.action_result:type_name -> mavsdk.rpc.action.ActionResult
	51, // 4: mavsdk.rpc.action.LandResponse.action_result:type_name -> mavsdk.rpc.action.ActionResult
	51, // 5: mavsdk.rpc.action.RebootResponse.action_result:type_name -> mavsdk.rpc.action.ActionResult
	51, // 6: mavsdk.rpc.action.ShutdownResponse.action_result:type_name -> mavsdk.rpc.action.ActionResult
	51, // 7: mavsdk.rpc.action.TerminateResponse.action_result:type_name -> mavsdk.rpc.action.ActionResult
	51, // 8: mavsdk.rpc.action.KillResponse.action_result:type_name -> mavsdk.rpc.action.ActionResult
	51, // 9: mavsdk.rpc.action.ReturnToLaunchResponse.action_result:type_name -> mavsdk.rpc.action.ActionResult
	51, // 10: mavsdk.rpc.action.GotoLocationResponse.action_result:type_name -> mavsdk.rpc.action.ActionResult
	0,  // 11: mavsdk.rpc.action.DoOrbitRequest.yaw_behavior:type_name -> mavsdk.rpc.action.OrbitYawBehavior
	51, // 12: mavsdk.rpc.action.DoOrbitResponse.action_result:type_name -> mavsdk.rpc.action.ActionResult
	51, // 13: mavsdk.rpc.action.HoldResponse.action_result:type_name -> mavsdk.rpc.action.ActionResult
	51, // 14: mavsdk.rpc.action.SetActuatorResponse.action_result:type_name -> mavsdk.rpc.action.ActionResult
	1,  // 15: mavsdk.rpc.action.SetRelayRequest.setting:type_name -> mavsdk.rpc.action.RelayCommand
	51, // 16: mavsdk.rpc.action.SetRelayResponse.action_result:type_name -> mavsdk.rpc.action.ActionResult
	51, // 17: mavsdk.rpc.action.TransitionToFixedwingResponse.action_result:type_name -> mavsdk.rpc.action.ActionResult
	51, // 18: mavsdk.rpc.action.TransitionToMulticopterResponse.action_result:type_name -> mavsdk.rpc.action.ActionResult
	51, // 19: mavsdk.rpc.action.GetTakeoffAltitudeResponse.action_result:type_name -> mavsdk.rpc.action.ActionResult
	51, // 20: mavsdk.rpc.action.SetTakeoffAltitudeResponse.action_result:type_name -> mavsdk.rpc.action.ActionResult
	51, // 21: mavsdk.rpc.action.GetReturnToLaunchAltitudeResponse.action_result:type_name -> mavsdk.rpc.action.ActionResult
	51, // 22: mavsdk.rpc.action.SetReturnToLaunchAltitudeResponse.action_result:type_name -> mavsdk.rpc.action.ActionResult
	51, // 23: mavsdk.rpc.action.SetCurrentSpeedResponse.action_result:type_name -> mavsdk.rpc.action.ActionResult
	51, // 24: mavsdk.rpc.action.SetGpsGlobalOriginResponse.action_result:type_name -> mavsdk.rpc.action.ActionResult
	51, // 25: mavsdk.rpc.action.SetHomeResponse.action_result:type_name -> mavsdk.rpc.action.ActionResult
	2,  // 26: mavsdk.rpc.action.ActionResult.result:type_name -> mavsdk.rpc.action.ActionResult.Result
	3,  // 27: mavsdk.rpc.action.ActionService.Arm:input_type -> mavsdk.rpc.action.ArmRequest
	5,  // 28: mavsdk.rpc.action.ActionService.ArmForce:input_type -> mavsdk.rpc.action.ArmForceRequest
	7,  // 29: mavsdk.rpc.action.ActionService.Disarm:input_type -> mavsdk.rpc.action.DisarmRequest
	9,  // 30: mavsdk.rpc.action.ActionService.Takeoff:input_type -> mavsdk.rpc.action.TakeoffRequest
	11, // 31: mavsdk.rpc.action.ActionService.Land:input_type -> mavsdk.rpc.action.LandRequest
	13, // 32: mavsdk.rpc.action.ActionService.Reboot:input_type -> mavsdk.rpc.action.RebootRequest
	15, // 33: mavsdk.rpc.action.ActionService.Shutdown:input_type -> mavsdk.rpc.action.ShutdownRequest
	17, // 34: mavsdk.rpc.action.ActionService.Terminate:input_type -> mavsdk.rpc.action.TerminateRequest
	19, // 35: mavsdk.rpc.action.ActionService.Kill:input_type -> mavsdk.rpc.action.KillRequest
	21, // 36: mavsdk.rpc.action.ActionService.ReturnToLaunch:input_type -> mavsdk.rpc.action.ReturnToLaunchRequest
	23, // 37: mavsdk.rpc.action.ActionService.GotoLocation:input_type -> mavsdk.rpc.action.GotoLocationRequest
	25, // 38: mavsdk.rpc.action.ActionService.DoOrbit:input_type -> mavsdk.rpc.action.DoOrbitRequest
	27, // 39: mavsdk.rpc.action.ActionService.Hold:input_type -> mavsdk.rpc.action.HoldRequest
	29, // 40: mavsdk.rpc.action.ActionService.SetActuator:input_type -> mavsdk.rpc.action.SetActuatorRequest
	31, // 41: mavsdk.rpc.action.ActionService.SetRelay:input_type -> mavsdk.rpc.action.SetRelayRequest
	33, // 42: mavsdk.rpc.action.ActionService.TransitionToFixedwing:input_type -> mavsdk.rpc.action.TransitionToFixedwingRequest
	35, // 43: mavsdk.rpc.action.ActionService.TransitionToMulticopter:input_type -> mavsdk.rpc.action.TransitionToMulticopterRequest
	37, // 44: mavsdk.rpc.action.ActionService.GetTakeoffAltitude:input_type -> mavsdk.rpc.action.GetTakeoffAltitudeRequest
	39, // 45: mavsdk.rpc.action.ActionService.SetTakeoffAltitude:input_type -> mavsdk.rpc.action.SetTakeoffAltitudeRequest
	41, // 46: mavsdk.rpc.action.ActionService.GetReturnToLaunchAltitude:input_type -> mavsdk.rpc.action.GetReturnToLaunchAltitudeRequest
	43, // 47: mavsdk.rpc.action.ActionService.SetReturnToLaunchAltitude:input_type -> mavsdk.rpc.action.SetReturnToLaunchAltitudeRequest
	45, // 48: mavsdk.rpc.action.ActionService.SetCurrentSpeed:input_type -> mavsdk.rpc.action.SetCurrentSpeedRequest
	47, // 49: mavsdk.rpc.action.ActionService.SetGpsGlobalOrigin:input_type -> mavsdk.rpc.action.SetGpsGlobalOriginRequest
	49, // 50: mavsdk.rpc.action.ActionService.SetHome:input_type -> mavsdk.rpc.action.SetHomeRequest
	4,  // 51: mavsdk.rpc.action.ActionService.Arm:output_type -> mavsdk.rpc.action.ArmResponse
	6,  // 52: mavsdk.rpc.action.ActionService.ArmForce:output_type -> mavsdk.rpc.action.ArmForceResponse
	8,  // 53: mavsdk.rpc.action.ActionService.Disarm:output_type -> mavsdk.rpc.action.DisarmResponse
	10, // 54: mavsdk.rpc.action.ActionService.Takeoff:output_type -> mavsdk.rpc.action.TakeoffResponse
	12, // 55: mavsdk.rpc.action.ActionService.Land:output_type -> mavsdk.rpc.action.LandResponse
	14, // 56: mavsdk.rpc.action.ActionService.Reboot:output_type -> mavsdk.rpc.action.RebootResponse
	16, // 57: mavsdk.rpc.action.ActionService.Shutdown:output_type -> mavsdk.rpc.action.ShutdownResponse
	18, // 58: mavsdk.rpc.action.ActionService.Terminate:output_type -> mavsdk.rpc.action.TerminateResponse
	20, // 59: mavsdk.rpc.action.ActionService.Kill:output_type -> mavsdk.rpc.action.KillResponse
	22, // 60: mavsdk.rpc.action.ActionService.ReturnToLaunch:output_type -> mavsdk.rpc.action.ReturnToLaunchResponse
	24, // 61: mavsdk.rpc.action.ActionService.GotoLocation:output_type -> mavsdk.rpc.action.GotoLocationResponse
	26, // 62: mavsdk.rpc.action.ActionService.DoOrbit:output_type -> mavsdk.rpc.action.DoOrbitResponse
	28, // 63: mavsdk.rpc.action.ActionService.Hold:output_type -> mavsdk.rpc.action.HoldResponse
	30, // 64: mavsdk.rpc.action.ActionService.SetActuator:output_type -> mavsdk.rpc.action.SetActuatorResponse
	32, // 65: mavsdk.rpc.action.ActionService.SetRelay:output_type -> mavsdk.rpc.action.SetRelayResponse
	34, // 66: mavsdk.rpc.action.ActionService.TransitionToFixedwing:output_type -> mavsdk.rpc.action.TransitionToFixedwingResponse
	36, // 67: mavsdk.rpc.action.ActionService.TransitionToMulticopter:output_type -> mavsdk.rpc.action.TransitionToMulticopterResponse
	38, // 68: mavsdk.rpc.action.ActionService.GetTakeoffAltitude:output_type -> mavsdk.rpc.action.GetTakeoffAltitudeResponse
	40, // 69: mavsdk.rpc.action.ActionService.SetTakeoffAltitude:output_type -> mavsdk.rpc.action.SetTakeoffAltitudeResponse
	42, // 70: mavsdk.rpc.action.ActionService.GetReturnToLaunchAltitude:output_type -> mavsdk.rpc.action.GetReturnToLaunchAltitudeResponse
	44, // 71: mavsdk.rpc.action.ActionService.SetReturnToLaunchAltitude:output_type -> mavsdk.rpc.action.SetReturnToLaunchAltitudeResponse
	46, // 72: mavsdk.rpc.action.ActionService.SetCurrentSpeed:output_type -> mavsdk.rpc.action.SetCurrentSpeedResponse
	48, // 73: mavsdk.rpc.action.ActionService.SetGpsGlobalOrigin:output_type -> mavsdk.rpc.action.SetGpsGlobalOriginResponse
	50, // 74: mavsdk.rpc.action.ActionService.SetHome:output_type -> mavsdk.rpc.action.SetHomeResponse
	51, // [51:75] is the sub-list for method output_type
	27, // [27:51] is the sub-list for method input_type
	27, // [27:27] is the sub-list for extension type_name
	27, // [27:27] is the sub-list for extension extendee
	0,  // [0:27] is the sub-list for field type_name
}

func init() { file_action_action_proto_init() }
func file_action_action_proto_init() {
	if File_action_action_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_action_action_proto_rawDesc), len(file_action_action_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   49,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_action_action_proto_goTypes,
		DependencyIndexes: file_action_action_proto_depIdxs,
		EnumInfos:         file_action_action_proto_enumTypes,
		MessageInfos:      file_action_action_proto_msgTypes,
	}.Build()
	File_action_action_proto = out.File
	file_action_action_proto_goTypes = nil
	file_action_action_proto_depIdxs = nil
}
